// Weapons data section ////////////////////////////////////////////////////////

#define SETS_NUMBER 45
#define MAX_WEAPONS_NUMBER 250
#define AUTO_SET 26

// Known weapon sets and player classes:

str playerClassNames[SETS_NUMBER] =
{
  "DoomPlayer",          //  0. Standard
  "PerkDPlayer",         //  1. PerK's Smoother Weapon Animations Enhanced, Smooth Doom (2018-01-13)
  "EriPlayer",           //  2. Eriguns - Standard weapons
  "AltPlayer",           //  3. Eriguns - Extended weapons
  "HellPlayer",          //  4. Eriguns - Hell weapons
  "BD_DoomPlayer",       //  5. Beautiful Doom
  "FDPlutPlayer",        //  6. Final Doomer - Plutonia
  "FDTNTPlayer",         //  7. Final Doomer - TNT
  "FDDoom2Player",       //  8. Final Doomer - Doom 2
  "FDAliensPlayer",      //  9. Final Doomer - Ancient Aliens
  "FDJPCPPlayer",        // 10. Final Doomer - JPCP
  "FDBTSXPlayer",        // 11. Final Doomer - BTSX
  "FasPlayer",           // 12. Faspons
  "HXRTCPlayer",         // 13. HXRTC Project
  "FKPlayer",            // 14. Kriegsland
  "ComplexDoomPlayer",   // 15. Complex Doom V27a3
  "SaturnPlayer",        // 16. Weapons of Saturn October 31, 2017
  "DoomMarine",          // 17. Hard-Doom v8.2f
  "HereticPlayer",       // 18. Heretic
  "ChexPlayer",          // 19. Chex Quest (Single Player)
  "StrifePlayer",        // 20. Strife
  "ArgPlayer",           // 21. Argent (v0.5.3)
  "64DoomPlayer",        // 22. Doom 64 'weapons only' X (updated 5-29-2016)
  "DoomPlayerFixed",     // 23. Responsive Weapons + Faster Weapon Switching
  "Xplayer",             // 24. Dead Marine v0.9.3
  "ParkourPlayer",       // 25. Parkour v1.1
  "Autodetected",        // 26. Autodetected
  "Purist",              // 27. Brutal Doom 21 test feb24 - Purist
  "BDoomer",             // 28. Brutal Doom - Rifle Start
  "Doomer2",             // 29. Brutal Doom - Pistal Start
  "TacticalDoomer",      // 30. Brutal Doom - Tactical Mode
  "CollabWeaponGuy",     // 31. Combined Arms v1.0
  "Trailblazer_Doom",    // 32. Trailblazer v1.4b - Doom
  "Trailblazer_Heretic", // 33. Trailblazer v1.4b - Heretic
  "Trailblazer_Hexen",   // 34. Trailblazer v1.4b - Hexen
  "WWColaPlayer",        // 35. WW-Cola3
  "HexenColaPlayer",     // 36. WW-Cola3 - Hexen
  "Eilidh",              // 37. Netronian Chaos v3
  "SquarePlayer",        // 38. Adventures of Square, Ep 1-2
  "CaptainBlazkowicz",   // 39. Doom Incarnate, v1.5
  "msx_player",          // 40. Project MSX 0.2a
  "DoomNukem",           // 41. Accessories to Murder
  "DoomRLMarine",        // 42. DoomRL Arsenal 1.05
  "WesternPlayer",       // 43. High Noon Drifter v1.2c
  "DoomPlayer",          // 44. Freedoom
};

int weaponCounts[SETS_NUMBER] =
{
  9,  // Standard
  10, // PerK's Smoother Weapon Animations Enhanced + Smooth Doom
  9, 13, 13, // Eriguns
  9,  // Beautiful Doom
  9, 9, 9, 9, 8, 9, // Final Doomer: Plutonia, TNT, Doom2, AA, JPCP, BTSX
  9,  // Faspons
  50, // HXRTC Project!
  22 + 5, // Kriegsland
  18, // Complex Doom
  11, // Weapons of Saturn
  14, // Hard-Doom
  8,  // Heretic
  8,  // Chex Quest
  8,  // Strife
  11, // Argent
  15, // Doom 64 X
  9,  // Responsive Weapons + Faster Weapon Switching
  9,  // Dead Marine
  12, // Parkour
  0,  // Special - autodetected
  9,  // Brutal Doom - Purist
  22, // Brutal Doom - BDoomer
  22, // Brutal Doom - Doomer2
  22, // Brutal Doom - TacticalDoomer
  12, // Combined Arms
  12, // Trailblazer - Doom
  12, // Trailblazer - Heretic
  12, // Trailblazer - Hexen
  8,  // WW-Cola3
  8,  // WW-Cola3 - Hexen
  24, // Netronian Chaos
  10, // Adventures of Square
  16, // Doom Incarnate
  8,  // Project MSX
  10, // Accessories to Murder
  217, // DoomRL Arsenal
  11, // High Noon Drifter
  9,  // Freedoom
};

int slots[SETS_NUMBER][MAX_WEAPONS_NUMBER] =
{
  { 1, 1, 2, 3, 3, 4, 5, 6, 7 }, // Standard

  // PerK's Smoother Weapon Animations Enhanced + Smooth Doom
  { 1, 1, 2, 2, 3, 3, 4, 5, 6, 7 },

  // Eriguns
  { 1, 1, 2, 3, 3, 4, 5, 6, 7 },
  { 1, 1, 2, 3, 3, 3, 4, 4, 5, 5, 6, 7, 8 },
  { 1, 1, 2, 2, 3, 4, 5, 6, 6, 7, 8, 8, 9 },

  { 1, 1, 2, 3, 3, 4, 5, 6, 7 }, // Beautiful Doom

  // Final Doomer
  { 1, 1, 2, 3, 3, 4, 5, 6, 7 },
  { 1, 1, 2, 3, 3, 4, 5, 6, 7 },
  { 1, 1, 2, 3, 3, 4, 5, 6, 7 },
  { 1, 1, 2, 3, 3, 4, 5, 6, 7 },
  { 1, 2, 3, 3, 4, 5, 6, 7 },
  { 1, 1, 2, 3, 3, 4, 5, 6, 7 },

  { 1, 1, 2, 3, 3, 4, 5, 6, 7 }, // Faspons

  { // HXRTC Project
    1, 1, 1, 1, 1, 1,
    2, 2, 2, 2, 2, 2,
    3, 3, 3, 3, 3,
    4, 4, 4, 4, 4, 4,
    5, 5, 5, 5, 5,
    6, 6, 6, 6, 6,
    7, 7, 7, 7, 7,
    8, 8, 8, 8, 8,
    9, 9, 9, 9, 9,
    0, 0
  },

  { // Kriegsland
    1, 1, 1,
    2, 2, 2,
    3, 3,
    4, 4,
    5, 5, 5,
    6, 6, 6,
    7, 7, 7,
    8, 8, 8,
    9, 9, 9, 9, 9, // cross akimbos
  },

  { // Complex Doom
    1, 1,
    2,
    3, 3, 3, 3,
    4, 4,
    5, 5,
    6, 6, 6,
    7, 7, 7,
    8,
  },

  { 1, 1, 2, 2, 3, 3, 4, 4, 5, 6, 7 }, // Weapons of Saturn

  { 1, 1, 2, 3, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7 }, // Hard-Doom

  { 1, 1, 2, 3, 4, 5, 6, 7 }, // Heretic

  { 1, 1, 2, 3, 4, 5, 6, 7 }, // Chex Quest

  { 1, 2, 3, 4, 5, 6, 7, 8 }, // Strife

  { 1, 1, 2, 3, 3, 4, 4, 5, 6, 6, 7 }, // Argent

  { 1, 1, 2, 2, 3, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7 }, // Doom 64 X

  { 1, 1, 2, 3, 3, 4, 5, 6, 7 }, // Responsive Weapons + Faster Weapon Switching

  { 1, 1, 2, 3, 3, 4, 5, 6, 7 }, // Dead Marine

  { 1, 1, 2, 2, 3, 3, 4, 5, 6, 7, 8, 9 }, // Parkour

  { }, // Special - autodetected

  { 1, 1, 2, 3, 3, 4, 5, 6, 7 }, // Brutal Doom - Purist
  { 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5, 6, 6, 7, 7, 7, 8, 8 }, // BDoomer
  { 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5, 6, 6, 7, 7, 7, 8, 8 }, // Doomer2
  { 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5, 6, 6, 7, 7, 7, 8, 8 }, // Tactical

  { 1, 1, 2, 3, 3, 4, 5, 6, 7, 8, 8, 8 }, // Combined Arms

  { 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 7 }, // Trailblazer
  { 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 7 },
  { 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 7 },

  { 1, 2, 2, 3, 4, 5, 6, 7 }, // WW-Cola3
  { 1, 2, 2, 3, 4, 5, 6, 7 }, // WW-Cola3 - Hexen

  { // Netronian Chaos
    1, 1, 1,
    2, 2, 2,
    3, 3, 3,
    4, 4, 4,
    5, 5, 5,
    6, 6, 6,
    7, 7, 7,
    8, 8, 8
  },

  { 1, 1, 2, 2, 3, 3, 4, 5, 6, 7 }, // Adventures of Square

  { // Doom Incarnate
    1, 1,
    2, 2,
    3, 3, 3,
    4, 4,
    5, 5,
    6, 6,
    7, 7,
    9
  },

  { 1, 2, 3, 4, 5, 6, 7, 8 }, // Project MSX

  { 1, 2, 2, 2, 3, 3, 4, 5, 6, 7 }, // Accessories to Murder

  { // DoomRL Arsenal
    1, 1, 1, 1, 1, 1,
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
    3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
    4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
    5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
    6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
    7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
  },

  { 1, 1, 2, 3, 3, 4, 4, 5, 6, 7, 0 }, // High Noon Drifter

  { 1, 1, 2, 3, 3, 4, 5, 6, 7 }, // Freedoom

};

str names[SETS_NUMBER][MAX_WEAPONS_NUMBER] =
{
  { // Standard
    "Chainsaw", "Fist",
    "Pistol",
    "SuperShotgun", "Shotgun",
    "Chaingun",
    "RocketLauncher",
    "PlasmaRifle",
    "BFG9000"
  },

  { // PerK's Smoother Weapon Animations Enhanced + Smooth Doom
    "Z86Chainsaw", "PerkFist",
    "Rifle", "PerkPistol",
    "PerkSuperShotgun", "PerkShotgun",
    "Z86Chaingun",
    "PerkRocketLauncher",
    "BloxPlasmaRifle",
    "Z86BFG9000"
  },

  {
    "EriChainsaw", "EriFist",
    "EriPistol",
    "EriSuperShotgun",
    "EriShotgun",
    "EriMachinegun",
    "EriRocketLauncher",
    "EriPlasmaRifle",
    "EriBFG9000"
  },
  {
    "EriChainsaw", "EriFist",
    "AltPistol",
    "EriAutoShotgun", "AltSuperShotgun", "EriShotgun",
    "EriGatlingGun", "EriMachinegun",
    "EriMissileLauncher", "EriRocketLauncher",
    "EriPlasmaRifle",
    "EriBFG9000",
    "EriGrenadeLauncher"
  },
  {
    "EriBlade", "EriFist",
    "EriSuperImmolator", "EriImmolator",
    "EriBloodbane",
    "EriNailgun",
    "EriMauler",
    "EriHellforge", "EriIrebolt",
    "EriCaster",
    "EriHydra", "EriBasilisk",
    "EriSoulreaver"
  },

  {
    "BD_Chainsaw", "BD_Fist",
    "BD_Pistol",
    "BD_SuperShotgun", "BD_Shotgun",
    "BD_Chaingun",
    "BD_RocketLauncher",
    "BD_PlasmaRifle",
    "BD_BFG9000"
  },

  {
    "FDPlutChainsaw", "FDPlutFist",
    "FDPlutPistol",
    "FDPlutSuperShotgun", "FDPlutShotgun",
    "FDPlutChaingun",
    "FDPlutRocketLauncher",
    "FDPlutPlasmaRifle",
    "FDPlutBFG9000"
  },
  {
    "FDTNTChainsaw", "FDTNTFist",
    "FDTNTPistol",
    "FDTNTSuperShotgun", "FDTNTShotgun",
    "FDTNTChaingun",
    "FDTNTRocketLauncher",
    "FDTNTPlasmaRifle",
    "FDTNTBFG9000"
  },
  {
    "FDDoom2Chainsaw", "FDDoom2Fist",
    "FDDoom2Pistol",
    "FDDoom2SuperShotgun", "FDDoom2Shotgun",
    "FDDoom2Chaingun",
    "FDDoom2RocketLauncher",
    "FDDoom2PlasmaRifle",
    "FDDoom2BFG9000"
  },
  {
    "FDAliensChainsaw", "FDAliensFist",
    "FDAliensPistol",
    "FDAliensSuperShotgun", "FDAliensShotgun",
    "FDAliensChaingun",
    "FDAliensRocketLauncher",
    "FDAliensPlasmaRifle",
    "FDAliensBFG9000"
  },
  {
    "FDJPCPFist",
    "FDJPCPPistol",
    "FDJPCPSuperShotgun", "FDJPCPShotgun",
    "FDJPCPChaingun",
    "FDJPCPRocketLauncher",
    "FDJPCPPlasmaRifle",
    "FDJPCPBFG9000"
  },
  {
    "FDBTSXChainsaw", "FDBTSXFist",
    "FDBTSXPistol",
    "FDBTSXSuperShotgun", "FDBTSXShotgun",
    "FDBTSXChaingun",
    "FDBTSXRocketLauncher",
    "FDBTSXPlasmaRifle",
    "FDBTSXBFG9000"
  },

  {
    "Motorsaw", "Knuckles",
    "CombatRifle",
    "DoubleBarrel", "Riotgun",
    "Minigun",
    "RPG",
    "PulseRifle",
    "BFG"
  },

  {
    "Z-Gun", "DoomChainsaw", "Axe", "Knife", "DoubleKnuckles", "OmicronRaygun",
    "LightMachinegun", "MP40", "DualColt1911", "Colt1911", "DualBerettas", "Beretta",
    "W-Shotgun", "AutoShotgun", "QuadShotgun", "CoachGun", "RiotShotgun",
    "HeavyChaingun", "M134Minigun", "DemonkillerCarbine", "M24SniperRifle", "DualCombatRifles", "CombatRifle",
    "MultiElementalCannon", "CryogenicRepeater", "NapalmLauncher", "SawThrower", "Saturn-V",
    "GatlingLasergun", "DualPulseRifles", "PulseRifle", "DualPlasmaZappers", "PlasmaZapper",
    "BlackHoleMaker", "BFG-X", "RailgunV20", "NeedleBuster", "ProtoBlaster",
    "ChillyIceBombard", "FlameCannon", "ChillerCrossbow", "NightmareDoubleRaygun", "HellMissileLauncher",
    "AcidArbalest", "ToxicWand", "EvilWarriorShield", "UACChemicalSpray", "BlowGun",
    "LandMineWeapon", "HandGrenadeWeapon",
  },

  { // Kriegsland
    "HDGrenades", "HDChainsaw", "HDKnife",
    "HDBlaster", "HDHandgun", "HDPistol",
    "HDSuperShotgun", "HDShotgun",
    "HDChaingun", "HDMachinegun",
    "HDPanzerfaust", "HDFlareGun", "HDRocketLauncher",
    "HDSonicGun", "HDLightningGun", "HDPlasmaRifle",
    "HDLaserGun", "HDLurdinha", "HDBFG9000",
    "HDCarbine", "HDGewehr", "HDRifle",
    "HDCrossAkimbo5", "HDCrossAkimbo4", "HDCrossAkimbo3", "HDCrossAkimbo2", "HDCrossAkimbo1",
  },

  { // Complex Doom
    "Chainsaw ", "Melee",
    "Handgun",
    "Quad Barrel Shotgun", "Double Barrel Shotgun", "Assault Shotgun", "Combat Shotgun",
    "Minigun ", "Assault Rifle",
    "Grenade Launcher", "Rocket Launcher",
    "Railgun ", "Demon Tech Rifle", "Plasma Rifle",
    "Demon Tech BFG10K", "BFG10K ", "BFG9500",
    "MP40",
  },

  { // Weapons of Saturn
    "Motorsaw", "Knuckles",
    "1911", "Beretta",
    "Coachgun", "Riotgun",
    "Minigun", "MachineRifle",
    "SaturnV",
    "NovaRifle",
    "TITAN",
  },

  { // Hard-Doom
    "Chainsaw~", "Fist~",
    "Pistol~",
    "Quad-Shotgun", "SuperShotgun~", "Shotgun~",
    "Minigun~", "Chaingun~",
    "GrenadeLauncher~", "RocketLauncher~",
    "PlasmaRifle~", "Sonic Railgun",
    "BFG10K~", "BFG9000~",
  },

  { // Heretic
    "Gauntlets", "Staff",
    "GoldWand",
    "Crossbow",
    "Blaster",
    "SkullRod",
    "PhoenixRod",
    "Mace",
  },

  { // Chex Quest
    "SuperBootspork",
    "Bootspoon",
    "MiniZorcher",
    "LargeZorcher",
    "RapidZorcher",
    "ZorchPropulsor",
    "PhasingZorcher",
    "LAZDevice",
  },

  { // Strife
    "PunchDagger",
    "StrifeCrossbow",
    "AssaultGun",
    "MiniMissileLauncher",
    "StrifeGrenadeLauncher",
    "FlameThrower",
    "Mauler",
    "Sigil",
  },

  { // Argent
    "ArgChainsaw",
    "ArgFist",
    "ArgPistol",
    "ArgSuperShotgun",
    "ArgShotgun",
    "ArgChaingun",
    "ArgHeavyAR",
    "ArgRocketLauncher",
    "ArgGaussCannon",
    "ArgPlasmaRifle",
    "ArgBFG9000",
  },

  { // Doom 64 X
    "64Chainsaw", "64Fist",
    "64Uzi", "64Pistol",
    "64Devastator", "64SuperShotgun", "64Shotgun",
    "64Nailgun", "64Chaingun",
    "64Flamethrower", "64RocketLauncher",
    "64Railgun", "64PlasmaRifle",
    "Unmaker", "64BFG9000",
  },

  { // Responsive Weapons + Faster Weapon Switching
    "ChainsawFixed", "FistFixed",
    "PistolFixed",
    "SuperShotgunFixed", "ShotgunFixed",
    "ChaingunFixed",
    "RocketLauncherFixed",
    "PlasmaRifleFixed",
    "BFG9000Fixed"
  },

  { // Dead Marine
    "XtremeSaw", "Xtremefist",
    "XtremePistol",
    "XtremeSSG", "XtremeShotgun",
    "XtremeChaingun",
    "XtremeRLauncher",
    "XtremePlasma",
    "XtremeBFG"
  },

  { // Parkour
    "PkChainsaw", "PkFist",
    "PkPistolAkimbo", "PkPistol",
    "PkDoubleShotguns", "PkShotgun",
    "PkChaingun",
    "PkRocketLauncher",
    "PkPlasmaRifle",
    "PkBFG9000",
    "PkCyberLauncher",
    "PkSuperChain",
  },

  { }, // Special - autodetected

  { // Brutal Doom Purist
    "ClassicSaw", "ClassicFist",
    "ClassicPistol",
    "ClassicSSG", "ClassicShotgun",
    "ClassicChaingun",
    "ClassicRocketLauncher",
    "ClassicPlasmaRifle",
    "VanillaBFG9000"
  },

  { // Brutal Doom - BDoomer
    "Melee_Attacks", "Chain_saw", "BrutalAxe",
    "MP40", "BrutalSMG", "BrutalPistol",
    "SSG", "Shot_Gun", "AssaultShotgun",
    "HitlersBuzzsaw", "Minigun", "Rifle", "Machinegun",
    "Rocket_Launcher", "GrenadeLauncher",
    "Plasma_Gun", "Railgun",
    "BIG_FUCKING_GUN", "Unmaker", "BFG10k",
    "FlameCannon", "HellishMissileLauncher"
  },

  { // Brutal Doom - Doomer2
    "Melee_Attacks", "Chain_saw", "BrutalAxe",
    "MP40", "BrutalSMG", "BrutalPistol",
    "SSG", "Shot_Gun", "AssaultShotgun",
    "HitlersBuzzsaw", "Minigun", "Rifle", "Machinegun",
    "Rocket_Launcher", "GrenadeLauncher",
    "Plasma_Gun", "Railgun",
    "BIG_FUCKING_GUN", "Unmaker", "BFG10k",
    "FlameCannon", "HellishMissileLauncher"
  },

  { // Brutal Doom - TacticalDoomer
    "Melee_Attacks", "Chain_saw", "BrutalAxe",
    "MP40", "BrutalSMG", "BrutalPistol",
    "SSG", "Shot_Gun", "AssaultShotgun",
    "HitlersBuzzsaw", "Minigun", "Rifle", "Machinegun",
    "Rocket_Launcher", "GrenadeLauncher",
    "Plasma_Gun", "Railgun",
    "BIG_FUCKING_GUN", "Unmaker", "BFG10k",
    "FlameCannon", "HellishMissileLauncher"
  },

  { // Combined Arms
    "SkillAxe", "CFSFists",
    "D3PS",
    "particlesmasher", "BitchinShotgun",
    "Gnasher",
    "CygnusRL",
    "BusterRifle",
    "daibatana",
    "havocrebounder", "tsbrick", "FlareGun"
  },

  { // Trailblazer
    "Macheterang", "SpikebombWeapon",
    "Colts", "Sidekick",
    "Fleshrend", "ChromeJustice",
    "Leadspitter", "FMG",
    "Bitchmaker", "Patriarch",
    "Skullthrottle",
    "Nutcracker",
  },
  { // Trailblazer
    "Macheterang", "SpikebombWeapon",
    "Colts", "Sidekick",
    "Fleshrend", "ChromeJustice",
    "Leadspitter", "FMG",
    "Bitchmaker", "Patriarch",
    "Skullthrottle",
    "Nutcracker",
  },
  { // Trailblazer
    "Macheterang", "SpikebombWeapon",
    "Colts", "Sidekick",
    "Fleshrend", "ChromeJustice",
    "Leadspitter", "FMG",
    "Bitchmaker", "Patriarch",
    "Skullthrottle",
    "Nutcracker",
  },

  { // WW-Cola3
    "ColaHandgun",
    "PumpShotgun", "DualPumpShotgun",
    "CardThrower",
    "PlasmaAutorifle",
    "MissileLauncher",
    "Piledriver",
    "ToothpasteLaser",
  },
  { // WW-Cola3
    "ColaHandgun",
    "PumpShotgun", "DualPumpShotgun",
    "CardThrower",
    "PlasmaAutorifle",
    "MissileLauncher",
    "Piledriver",
    "ToothpasteLaser",
  },

  { // Netronian Chaos
    "LB1000PileBanger", "AnaikaDagger", "M101Blade",
    "EG10HeavyPistol", "V57BurstPistol", "V96ServicePistol",
    "FASR33AssaultSupporter", "VS4Sweeper", "VS2Riotgun",
    "PAG20PDW", "V80BSMG", "V88Carbine",
    "VARACarbine", "AG100Machinegun", "V74ARifle",
    "M12FMGR", "V32AARifle", "V50MLauncher",
    "M189Auto", "V99AThrower", "VE1Coilgun",
    "HeavyBarrel", "VM201TD", "Ver110VC"
  },

  { // Adventures of Square
    "PaintGuns", "PaintGun",
    "Oozis", "Oozi",
    "Quadcannon", "Shotbow",
    "PaintCannon",
    "HellShellLauncher",
    "Sceptre",
    "Defibrillator"
  },

  { // Doom Incarnate
    "SMG", "Handgun",
    "Paratrooper", "ScytheMagnum",
    "Grimmhammer", "DoubleShotgun", "InfernoShotgun",
    "GatlingGun", "AssaultRifle",
    "NapalmKraftWerk", "Kampfpistole",
    "LaserKraftWerk", "PlazmaRifle",
    "Ubergewehr", "Lasergewehr",
    "CrossedWield"
  },

  { // Project MSX
    "RegularFists",
    "golampistol",
    "hydrashotgun",
    "barracudarifle",
    "raptorshotgun",
    "tauruscannon",
    "chimerarifle",
    "orionSniper"
  },

  { // Accessories to Murder
    "Sledge",
    "Revolver", "DNDualPistol", "DNPistol",
    "TrenchShotgun", "DoubleShotgun",
    "DNRifle",
    "DNRocketLauncher",
    "DNChaingun",
    "DNBFG"
  },

  { // DoomRL Arsenal
    "RLEnergysaw",
    "RLPiercingChainsaw",
    "RLChainsaw",
    "RLRipper",
    "RLDoubleChainsaw",
    "RLFistRedux",
    "RLNanomanufactureAmmoDesertEagle",
    "RLNanoManufactureAmmoMarksmanPistol",
    "RLNanomanufactureAmmoCombatPistol",
    "RLNanomanufactureAmmoBlaster",
    "RLNanoManufactureAmmoPistol",
    "RLHeavyPulseBlaster",
    "RLOverchargedBlaster",
    "RLPlasmaDesertEagle",
    "RLPlasmaCombatPistol",
    "RLPlasmaPistol",
    "RLStormBlaster",
    "RLStormDesertEagle",
    "RLStormMarksmanPistol",
    "RLStormCombatPistol",
    "RLStormPistol",
    "RLHighPowerPP7",
    "RLHighPowerHuntingRevolver",
    "RLHighPowerDesertEagle",
    "RLHighPowerMarksmanPistol",
    "RLHighPowerCombatPistol",
    "RLHighPowerBlaster",
    "RLHighPowerPistol",
    "RLSpeedloaderPistol",
    "RLSilencedPistol",
    "RLNeuralStunner",
    "RLDeathsGaze",
    "RLTrigun",
    "RLHellsingARMSCasull",
    "RLAntiFreakJackal",
    "RLGrammatonClericBeretta",
    "RLUnknownHerald",
    "RLMysteriousMagnum",
    "RLPP7",
    "RLHuntingRevolver",
    "RLDesertEagle",
    "RLMarksmanPistol",
    "RLCombatPistol",
    "RLBlaster",
    "RLPistol",
    "RLConquerorShotgun",
    "RLMegatonShotgun",
    "RLNanoShrapnelAssaultShotgun",
    "RLNanoShrapnelSuperShotgun",
    "RLNanoShrapnelDoubleShotgun",
    "RLNanoShrapnelCombatShotgun",
    "RLNanoShrapnelShotgun",
    "RLAutoDoubleShotgun",
    "RLAutoShotgun",
    "RLFocusedDoubleShotgun",
    "RLPlasmaticShrapnelHuntingShotgun",
    "RLPlasmaticShrapnelAssaultShotgun",
    "RLPlasmaticShrapnelSuperShotgun",
    "RLPlasmaticShrapnelDoubleShotgun",
    "RLPlasmaticShrapnelCombatShotgun",
    "RLPlasmaticShrapnelShotgun",
    "RLHeavyHuntingShotgun",
    "RLHeavyAssaultShotgun",
    "RLHeavySuperShotgun",
    "RLHeavyDoubleShotgun",
    "RLHeavyCombatShotgun",
    "RLHeavyShotgun",
    "RLTacticalShotgun",
    "RLElephantGun",
    "RLShredderShotgun",
    "RLShredderPistol",
    "RLJudgeOfTheDead",
    "RLMarathonShotguns",
    "RLSteelBeast",
    "RLQuadShotgun",
    "RLFragShotgun",
    "RLJackhammer",
    "RLHuntingShotgun",
    "RLSuperShotgun",
    "RLAssaultShotgun",
    "RLDoubleShotgun",
    "RLCombatShotgun",
    "RLShotgun",
    "RLNanoManufactureAmmoUzi",
    "RLNanoManufactureAmmoMinigun",
    "RLNanomanufactureAmmoBattleRifle",
    "RLNanoManufactureAmmoChaingun",
    "RLAntiMaterielRifle",
    "RLSuperMachinegun",
    "RLBurstCannonUzi",
    "RLBurstCannonMinigun",
    "RLBurstCannonBattleRifle",
    "RLBurstCannonChaingun",
    "RLAssaultRifleUzi",
    "RLAssaultRifleMinigun",
    "RLAssaultRifleBattleRifle",
    "RLAssaultRifleChaingun",
    "RLBulletstormRifle",
    "RLBulletstormChaingun",
    "RLStormUzi",
    "RLHighPowerRCP90",
    "RLHighPowerThompson",
    "RLHighPowerVanguardRifle",
    "RLHighPowerMarksmanRifle",
    "RLHighPowerUzi",
    "RLHighPowerMinigun",
    "RLHighPowerBattleRifle",
    "RLHighPowerChaingun",
    "RLSniperRifle",
    "RLGatlingGun",
    "RLStealthRifle",
    "RLSoulstormRifle",
    "RLNanomachicArmamentGenerator",
    "RLWidowmakerSMG",
    "RLMarathonAssaultRifle",
    "RLRCP90",
    "RLThompson",
    "RLVanguardRifle",
    "RLMarksmanRifle",
    "RLUzi",
    "RLMinigun",
    "RLBattleRifle",
    "RLChaingun",
    "RLDemolitionAmmoUzi",
    "RLDemolitionAmmoMinigun",
    "RLDemolitionAmmoDesertEagle",
    "RLDemolitionAmmoMarksmanPistol",
    "RLDemolitionAmmoCombatPistol",
    "RLDemolitionAmmoChaingun",
    "RLDemolitionAmmoBattleRifle",
    "RLDemolitionAmmoPistol",
    "RLNanoManufactureAmmoNapalmLauncher",
    "RLNanoManufactureAmmoMissileLauncher",
    "RLNanomanufactureAmmoTristarBlaster",
    "RLNanomanufactureAmmoRocketLauncher",
    "RLIncinerationDeviceLauncher",
    "RLLaserPulseLauncher",
    "RLInfusionLauncher",
    "RLClusterBombLauncher",
    "RLAutocannon",
    "RLMotherInLaw",
    "RLGrenadeLauncher",
    "RLMiniMissilePistol",
    "RLTacticalRocketLauncher",
    "RLHighPowerTristarBlaster",
    "RLShrapnelCannon",
    "RLMicroLauncher",
    "RLHurricaneCannon",
    "RLMIRVLauncher",
    "RLRevenantsLauncher",
    "RLTantrumCannon",
    "RLNapalmLauncher",
    "RLMissileLauncher",
    "RLTristarBlaster",
    "RLRocketLauncher",
    "RLNanoManufactureAmmoLaserRifle",
    "RLNanomanufactureAmmoPlasmaRifle",
    "RLLaserMinigun",
    "RLPlasmaCannon",
    "RLGaussRifle",
    "RLVoltgun",
    "RLPlasmaRefractor",
    "RLNanoShrapnelPlasmaShotgun",
    "RLBurstCannonNuclearPlasmaRifle",
    "RLBurstCannonLaserRifle",
    "RLBurstCannonPlasmaRifle",
    "RLAssaultRifleNuclearPlasmaRifle",
    "RLAssaultRifleLaserRifle",
    "RLAssaultRiflePlasmaRifle",
    "RLNuclearPlasmaShotgun",
    "RLPlasmaShotgunMkII",
    "RLLaserShotgun",
    "RLNuclearPlasmaRifleMkII",
    "RLPlasmaRifleMkII",
    "RLHyperblaster",
    "RLSuperchargedNuclearPlasmaPistol",
    "RLPlasmaUzi",
    "RLPlasmaMarksmanPistol",
    "RLStormNuclearPlasmaPistol",
    "RLPlasmaticShrapnelPlasmaShotgun",
    "RLHighPowerNuclearPlasmaRifle",
    "RLHighPowerNuclearPlasmaPistol",
    "RLHighPowerLaserRifle",
    "RLHighPowerPlasmaRifle",
    "RLHeavyPlasmaShotgun",
    "RLNuclearPlasmaRevolver",
    "RLFlamethrower",
    "RLDuke2Rifle",
    "RLUnmaker",
    "RLHellsReign",
    "RLNuclearOnslaught",
    "RLChameleonRifle",
    "RLSussGun",
    "RLPlasmaRedirectionCannon",
    "RLLightweaver",
    "RLRailgun",
    "RLCombatTranslocator",
    "RLNuclearPlasmaRifle",
    "RLNuclearPlasmaPistol",
    "RLLaserRifle",
    "RLPlasmaShotgun",
    "RLPlasmaRifle",
    "RLZeusCannon",
    "RLNuclearBiggestFuckingGun",
    "RLBiggestFuckingGun",
    "RLNuclearVBFG9000",
    "RLVBFG9000",
    "RLHighPowerNuclearBFG9000",
    "RLHighPowerBFG9000",
    "RLBFGInfinity",
    "RLRealityDistortionArray",
    "RLBaronBlaster",
    "RLParticleBeamCannon",
    "RLNullPointer",
    "RLBFG10K",
    "RLNuclearBFG9000",
    "RLBFG9000"
  },

  { // High Noon Drifter
    "Boomerang", "Bow",
    "Revolver",
    "Coachgun", "Winchester",
    "SMGs", "SMG",
    "Grenades",
    "DarkStaff",
    "Artifact",
    "DoubleWhips",
  },

  { // Freedoom
    "Chainsaw", "Fist",
    "Pistol",
    "SuperShotgun", "Shotgun",
    "Chaingun",
    "RocketLauncher",
    "PlasmaRifle",
    "BFG9000"
  },

}; // end of actor/class names /////////////////////////////////////////////////

str printableNames[SETS_NUMBER][MAX_WEAPONS_NUMBER] =
{
  { // Doom
    "Chainsaw", "Brass Knuckles",
    "Pistol",
    "Super Shotgun", "Shotgun",
    "Chaingun",
    "Rocket Launcher",
    "Plasma Rifle",
    "BFG 9000"
  },

  { // PerK's Smoother Weapon Animations Enhanced + Smooth Doom
    "Chainsaw", "Fist",
    "Rifle", "Pistol",
    "Super Shotgun", "Shotgun",
    "Chaingun",
    "Rocket Launcher",
    "Plasma Rifle",
    "BFG9000"
  },

  { // Eriguns
    "Chainsaw", "Fist",
    "Pistol",
    "Super Shotgun", "Shotgun",
    "Chaingun",
    "Rocket Launcher",
    "Plasma Rifle",
    "BFG9000"
  },
  {
    "Chainsaw", "Fist",
    "Pistol",
    "Auto Shotgun", "Super Shotgun", "Shotgun",
    "Gatling Gun", "Machinegun",
    "Missile Launcher", "Rocket Launcher",
    "Plasma Rifle",
    "BFG9000",
    "Grenade Launcher"
  },
  {
    "Vorpal Blade", "Fist",
    "Super Immolator", "Immolator",
    "Bloodbane",
    "Nailgun",
    "Mauler",
    "Hellforge", "Irebolt",
    "Soul Caster",
    "Hydra", "Basilisk",
    "Soul Reaver"
  },

  { // Beautiful Doom
    "Chainsaw", "Fist",
    "Pistol",
    "Super Shotgun", "Shotgun",
    "Chaingun",
    "Rocket Launcher",
    "Plasma Rifle",
    "BFG9000"
  },

  { // Final Doomer
    "Power Saw", "Melee",
    "Ol' Faithful",
    "Super Shotgun", "Scoped Shotgun",
    "Machine Gun",
    "Grenade Launcher",
    "Heavy Machine Gun",
    "Quantum Accelerator"
  },
  {
    "Halderman Device", "Melee",
    "Prototype Pistol",
    "Burst Shotgun", "Tactical Shotgun",
    "Dual Uzis",
    "Missile Launcher",
    "Maser",
    "Incursion Annihilator"
  },
  {
    "Chainsaw", "Melee",
    "Pistol",
    "Super Shotgun", "Shotgun",
    "Chaingun",
    "Rocket Launcher",
    "Plasma Rifle",
    "BFG 9000"
  },
  {
    "Stasis Bow", "Trench Knife",
    "Ancient Pistol",
    "Hybrid SSG", "Ancient Shotgun",
    "Ancient AK",
    "Photon Scepter",
    "Alien Elite Weapon",
    "Illuminator"
  },
  {
    "Katana",
    "Silenced Pistol",
    "Neutron Cascader", "Neutron Pulser",
    "Burst Needler",
    "Prism Cannon",
    "Ofuda Caster",
    "Onmyou Devastator"
  },
  {
    "NanoCore", "Power Fist",
    "Charge Pistol",
    "Machreaper", "Arc Blaster",
    "Pulse Rifle",
    "Pulse Cannon",
    "Plasma Vulcan",
    "X-Spark Cannon"
  },

  { // Faspons
    "Chainsaw", "Knuckles",
    "Combat Rifle",
    "Double Barrel Shotgun", "Riotgun",
    "Minigun",
    "RPG",
    "Pulse Rifle",
    "BFG9000"
  },

  {
    "Z-Gun", "Chainsaw", "Hatchet", "Knife", "Double Knuckles", "Omicron Raygun",
    "Light Machinegun", "MP40", "Dual Colt 1911", "Colt 1911", "Dual Berettas", "Beretta",
    "W-Shotgun", "Auto Shotgun", "Quad Shotgun", "Coach Gun", "Riot Shotgun",
    "Heavy Chaingun", "M134 Minigun", "Demonkiller Carbine", "M24 Sniper Rifle", "Dual Combat Rifles", "Combat Rifle",
    "Multi-Elemental Cannon", "Cryogenic Repeater", "Napalm Launcher", "Saw Thrower", "Saturn-V",
    "Gatling Lasergun", "Dual Pulse Rifles", "Pulse Rifle", "Dual Plasma Zappers", "Plasma Zapper",
    "Black Hole Maker", "BFG-X", "Railgun 2.0", "Needle Buster", "Proto Blaster",
    "Chilly Mancubus' Ice Bombard", "Mancubi's Flame Cannon", "Arctic Archer's Chiller Crossbow", "Nightmare Reaper's Double Raygun", "Skeleton's Hell Missile Launcher",
    "Acid Arbalest", "Toxic Wand", "Evil Warrior's Shield", "UAC Chemical Spray", "Poison Dart Blowgun",
    "Land Mine", "Hand Grenade",
  },

  { // Kriegsland
    "Stielhandgranate-68", "Elektroshocker", "Kampfmesser 84",
    "DL-44 FuturPistole-Blaster", "Mauser M972-S2", "Luger P-58",
    "Jadtfaust Wunderfilnte-8", "Luftwaffe DP-65",
    "MP-86s", "StG-60",
    "Panzerkreuz Mk. III", "Kampfpistole", "Lawine-6",
    "Schallkraftwerk", "Blitzgewehr", "Flammenfaust",
    "Ekelhaftwaffe", "MG-92", "VFR-245 Puls-Kanone",
    "Bombenschuss", "Gewehr-1953", "KAR 82a-2K",
    "Cross Thermals", "Cross Launchers", "Cross Machineguns", "Cross Shotguns", "Cross Pistols",
  },

  { // Complex Doom
    "Chainsaw", "Melee",
    "Handgun",
    "Quad Barrel Shotgun", "Double Barrel Shotgun", "Assault Shotgun", "Combat Shotgun",
    "Minigun", "Assault Rifle",
    "Grenade Launcher", "Rocket Launcher",
    "Railgun", "Demon Tech Rifle", "Plasma Rifle",
    "Demon Tech BFG10K", "BFG10K", "BFG9500",
    "MP40",
  },

  { // Weapons of Saturn
    "Chain Saw", "Knuckles",
    "1911", "Beretta",
    "Coach Gun", "Riot Gun",
    "Rotary Cannon", "Machine Rifle",
    "Saturn V",
    "Nova Rifle",
    "Titan",
  },

  { // Hard-Doom
    "Chainsaw", "Fist",
    "Pistol",
    "Quad-Shotgun", "Super Shotgun", "Shotgun",
    "Minigun", "Chaingun",
    "Grenade Launcher", "Rocket Launcher",
    "Plasma Rifle", "Sonic Railgun",
    "BFG10K", "BFG9000",
  },

  { // Heretic
    "Gauntlets of the Necromancer", "Staff",
    "Elven Wand",
    "Ethereal Crossbow",
    "Dragon Claw",
    "Hellstaff",
    "Phoenix Rod",
    "Firemace",
  },

  { // Chex Quest
    "Super Bootspork", "Spoon",
    "Mini Zorcher",
    "Large Zorcher",
    "Rapid Zorcher",
    "Zorch Propulsor",
    "Phasing Zorcher",
    "LAZ Device",
  },

  { // Strife
    "Dagger",
    "Crossbow",
    "Assault Gun",
    "Mini Missile Launcher",
    "Grenade Launcher",
    "Flame Thrower",
    "Mauler",
    "SIGIL",
  },

  { // Argent
    "Chainsaw",
    "Fists",
    "Pistol",
    "Super Shotgun",
    "Combat Shotgun",
    "Chaingun",
    "Heavy Assault Rifle",
    "Rocket Launcher",
    "Gauss Cannon",
    "Plasma Rifle",
    "BFG 9000",
  },

  { // Doom 64 X
    "Chainsaw", "Fist",
    "Uzi", "Pistol",
    "Devastator", "Super Shotgun", "Shotgun",
    "Nailgun", "Chaingun",
    "Flamethrower", "Rocket Launcher",
    "Railgun", "Plasma Rifle",
    "Unmaker", "BFG 9000",
  },

  { // Responsive Weapons + Faster Weapon Switching
    "Chainsaw", "Brass Knuckles",
    "Pistol",
    "Super Shotgun", "Shotgun",
    "Chaingun",
    "Rocket Launcher",
    "Plasma Rifle",
    "BFG 9000"
  },

  { // Dead Marine
    "Chainsaw", "Brass Knuckles",
    "Pistol",
    "Super Shotgun", "Shotgun",
    "Chaingun",
    "Rocket Launcher",
    "Plasma Rifle",
    "BFG 9000"
  },

  { // Parkour
    "Chainsaw", "Fists",
    "Akimbo Pistols", "Pistol",
    "Dual Sawnoffs", "Shotgun",
    "Chaingun",
    "Rocket Launcher",
    "Plasma Rifle",
    "BFG 9000",
    "Cyber Launcher",
    "Super Chaingun",
  },

  { }, // Special - autodetected

  { // Brutal Doom Purist
    "Chainsaw", "Brass Knuckles",
    "Pistol",
    "Super Shotgun", "Shotgun",
    "Chaingun",
    "Rocket Launcher",
    "Plasma Rifle",
    "BFG 9000"
  },

  { // Brutal Doom - BDoomer
    "Melee", "Chainsaw", "Axe",
    "MP40", "SMG", "Pistol",
    "SSG", "Shotgun", "AA-12 Assault Shotgun",
    "Hitler's Buzzsaw", "Minigun", "Assault Rifle", "Machine Gun",
    "Rocket Launcher", "Grenade Launcher",
    "Plasma Gun", "Railgun",
    "BFG-9000", "Unmaker", "BFG10K",
    "Flame Cannon", "Hellish Missile Launcher"
  },

  { // Brutal Doom - Doomer2
    "Melee", "Chainsaw", "Axe",
    "MP40", "SMG", "Pistol",
    "SSG", "Shotgun", "AA-12 Assault Shotgun",
    "Hitler's Buzzsaw", "Minigun", "Assault Rifle", "Machine Gun",
    "Rocket Launcher", "Grenade Launcher",
    "Plasma Gun", "Railgun",
    "BFG-9000", "Unmaker", "BFG10K",
    "Flame Cannon", "Hellish Missile Launcher"
  },

  { // Brutal Doom - TacticalDoomer
    "Melee", "Chainsaw", "Axe",
    "MP40", "SMG", "Pistol",
    "SSG", "Shotgun", "AA-12 Assault Shotgun",
    "Hitler's Buzzsaw", "Minigun", "Assault Rifle", "Machine Gun",
    "Rocket Launcher", "Grenade Launcher",
    "Plasma Gun", "Railgun",
    "BFG-9000", "Unmaker", "BFG10K",
    "Flame Cannon", "Hellish Missile Launcher"
  },

  { // Combined Arms
    "Lilk's Axe", "Fists",
    "Genka-12",
    "Particle Smasher", "Shotgun",
    "Mk. 2 'Gnasher' Nailgun",
    "Cygnus Rocket Launcher",
    "Buster Rifle",
    "Daibatana",
    "Havoc Rebounder", "Plakanomicon", "ZT Prototype Flare Gun"
  },

  { // Trailblazer
    "Macheterang", "Spikebombs",
    "Cradle & Grave", "Sidekick",
    "Fleshrend", "Chrome Justice",
    "Leadspitter", "F.M.G.",
    "Bitchmaker", "Patriarch",
    "Skullthrottle",
    "Nutcracker",
  },
  { // Trailblazer
    "Macheterang", "Spikebombs",
    "Cradle & Grave", "Sidekick",
    "Fleshrend", "Chrome Justice",
    "Leadspitter", "F.M.G.",
    "Bitchmaker", "Patriarch",
    "Skullthrottle",
    "Nutcracker",
  },
  { // Trailblazer
    "Macheterang", "Spikebombs",
    "Cradle & Grave", "Sidekick",
    "Fleshrend", "Chrome Justice",
    "Leadspitter", "F.M.G.",
    "Bitchmaker", "Patriarch",
    "Skullthrottle",
    "Nutcracker",
  },

  { // WW-Cola3
    "Marston R-1 Techvolver",
    "KS-23 Shotgun", "Dual KS-23 Shotguns",
    "Kare Brand Cards",
    "Plasma Autorifle",
    "Sidewinder Missile Launcher",
    "Piledriver",
    "Toothpaste Laser",
  },
  { // WW-Cola3
    "Marston R-1 Techvolver",
    "KS-23 Shotgun", "Dual KS-23 Shotguns",
    "Kare Brand Cards",
    "Plasma Autorifle",
    "Sidewinder Missile Launcher",
    "Piledriver",
    "Toothpaste Laser",
  },

  { // Netronian Chaos
    "Pile Banger Glove", "Anaika Hunting Daggers", "Digitalblade",
    "Heavy Caliber Pistol", "Burst Pistol", "Service Pistol",
    "Assault Supporter", "Hand Sweeper", "Riotgun",
    "Personal Defence Arm", "Burst SMG", "Machine Carbine",
    "Semi Auto Rifle", "Squad Support Gun", "Combat Rifle",
    "Cyro Grenade Bouncer", "Anti Armor Rifle", "Missile Launcher",
    "Full Auto LAWF", "Personal Annihilator", "Semi Coil Carbine",
    "Fierce Caliber", "Tri Desolator", "Heavy Vulcan"
  },

  { // Adventures of Square
    "Dual Paint Guns", "Paint Gun",
    "Dual Oozis", "Oozi",
    "Quad Cannon", "Shotbow",
    "Paintgun Cannon",
    "Hellshell Launcher",
    "Cresceptre",
    "Defibrillator"
  },

  { // Doom Incarnate
    "Sub-Machine Gun", "Handgun",
    "Paratrooper Rifle", "Scythe Magnum",
    "Grimmhammer", "Super Shotgun", "Inferno Shotgun",
    "Gatling Gun", "Assault Rifle",
    "NapalmKraftWerk", "Kampfpistole",
    "LaserKraftWerk", "Plasma Rifle",
    "Ubergewehr", "Lasergewehr",
    "Crossed Wield"
  },

  { // Project MSX
    "Fists",
    "Golam Pistol",
    "Hydra Shotgun",
    "Barracuda Rifle",
    "Raptor NailShotgun",
    "Taurus AutoCannon",
    "Chimaera Pulse Rifle",
    "Orion Gauss Cannon"
  },

  { // Accessories to Murder
    "Sledge Hammer",
    "Revolver", "Pistols (Akimbo)", "Pistol",
    "Shotgun", "Sawed-Off",
    "Assault Rifle",
    "Rocket Launcher",
    "Chaingun",
    "Bergmann Field Generator"
  },

  { // DoomRL Arsenal
    "Energysaw",
    "Nanoedge Chainsaw",
    "Chainsaw",
    "Ripper",
    "Double Chainsaw",
    "Unarmed",
    "Nanomachic Handcannon",
    "Nanomachic Marksman Pistol",
    "Nanomachic Combat Pistol",
    "Nanomachic Blaster",
    "Nanomachic Pistol",
    "Heavy Pulse Blaster",
    "Overcharged Blaster",
    "Plasma Handcannon",
    "Plasma Combat Pistol",
    "Plasma Pistol",
    "Storm Blaster",
    "Storm Handcannon",
    "Storm Marksman Pistol",
    "Storm Combat Pistol",
    "Storm Pistol",
    "High Power PP7",
    "High Power Hunting Revolver",
    "High Power Handcannon",
    "High Power Marksman Pistol",
    "High Power Combat Pistol",
    "High Power Blaster",
    "High Power Pistol",
    "Revolver",
    "Silenced Pistol",
    "Neural Stunner",
    "Death's Gaze",
    "Trigun",
    "Hellsing ARMS Casull",
    "Anti-Freak Jackal",
    "Grammaton Cleric Beretta",
    "Unknown Herald",
    "Mysterious Magnum",
    "PP7",
    "Hunting Revolver",
    "Handcannon",
    "Marksman Pistol",
    "Combat Pistol",
    "Blaster",
    "Pistol",
    "Conqueror Shotgun",
    "Megaton Shotgun",
    "Nano Assault Shotgun",
    "Nano Super Shotgun",
    "Nano Double Shotgun",
    "Nano Combat Shotgun",
    "Nano Shotgun",
    "Auto Double Shotgun",
    "Auto Shotgun",
    "Focused Double Shotgun",
    "Plasmatic Hunting Shotgun",
    "Plasmatic Assault Shotgun",
    "Plasmatic Super Shotgun",
    "Plasmatic Double Shotgun",
    "Plasmatic Combat Shotgun",
    "Plasmatic Shotgun",
    "Heavy Hunting Shotgun",
    "Heavy Assault Shotgun",
    "Heavy Super Shotgun",
    "Heavy Double Shotgun",
    "Heavy Combat Shotgun",
    "Heavy Shotgun",
    "Tactical Shotgun",
    "Elephant Gun",
    "Shredder Shotgun",
    "Shredder Pistol",
    "Judge of the Dead",
    "WSTE-M5 Shotguns",
    "Steel Beast",
    "Quad Shotgun",
    "Frag Shotgun",
    "Jackhammer",
    "Hunting Shotgun",
    "Super Shotgun",
    "Assault Shotgun",
    "Double Shotgun",
    "Combat Shotgun",
    "Shotgun",
    "Nanomachic Uzi",
    "Nanomachic Minigun",
    "Nanomachic Battle Rifle",
    "Nanomachic Chaingun",
    "Anti-materiel Rifle",
    "Super Machinegun",
    "Burst Uzi",
    "Burst Minigun",
    "Burst-Fire Rifle",
    "Burst Chaingun",
    "Assault Uzi",
    "Assault Minigun",
    "Scoped Rifle",
    "Assault Chaingun",
    "Bulletstorm Rifle",
    "Bulletstorm Chaingun",
    "Dual Uzis",
    "RC-P120",
    "High Power Tommygun",
    "High Power Vanguard Rifle",
    "High Power Marksman Rifle",
    "High Power Uzi",
    "High Power Minigun",
    "High Power Battle Rifle",
    "High Power Chaingun",
    "Sniper Rifle",
    "Gatling Gun",
    "Stealth Rifle",
    "Soulstorm Rifle",
    "Nanomachic Armament Generator",
    "Widowmaker SMG",
    "MA-75B Assault Rifle",
    "RC-P90",
    "Tommygun",
    "Vanguard Rifle",
    "Marksman Rifle",
    "Uzi",
    "Minigun",
    "Battle Rifle",
    "Chaingun",
    "Demolition Ammo Uzi",
    "Demolition Ammo Minigun",
    "Demolition Ammo Handcannon",
    "Demolition Ammo Marksman Pistol",
    "Demolition Ammo Combat Pistol",
    "Demolition Ammo Chaingun",
    "Demolition Ammo Battle Rifle",
    "Demolition Ammo Pistol",
    "Nanomachic Napalm Launcher",
    "Nanomachic Missile Launcher",
    "Nanomachic Tristar Blaster",
    "Nanomachic Rocket Launcher",
    "Incineration Device Launcher",
    "Defence Drone Launcher",
    "Plascharge Launcher",
    "Cluster Bomb Launcher",
    "Autocannon",
    "Mother-In-Law",
    "Grenade Launcher",
    "Mini-missile Pistol",
    "Tactical Rocket Launcher",
    "High Power Tristar Blaster",
    "Shrapnel Cannon",
    "Micro Launcher",
    "Hurricane Cannon",
    "MIRV Launcher",
    "Revenant's Launcher",
    "Quantum Tantrum Cannon",
    "Napalm Launcher",
    "Missile Launcher",
    "Tristar Blaster",
    "Rocket Launcher",
    "Nanomachic Laser Rifle",
    "Nanomachic Plasma Rifle",
    "Laser Minigun",
    "Plasma Cannon",
    "Gauss Rifle",
    "Voltgun",
    "Plasma Refractor",
    "Nano Plasma Shotgun",
    "Burst Nuclear Plasma Rifle",
    "Burst Laser Rifle",
    "Burst Plasma Rifle",
    "Assault Nuclear Plasma Rifle",
    "Assault Laser Rifle",
    "Assault Plasma Rifle",
    "Nuclear Plasma Shotgun",
    "Plasma Shotgun Mk. II",
    "Laser Shotgun",
    "Nuclear Plasma Rifle Mk. II",
    "Plasma Rifle Mk. II",
    "Hyperblaster",
    "Supercharged Nuclear Plasma Pistol",
    "Plasma Uzi",
    "Plasma Marksman Pistol",
    "Storm Nuclear Plasma Pistol",
    "Overcharged Plasma Shotgun",
    "High Power Nuclear Plasma Rifle",
    "High Power Nuclear Plasma Pistol",
    "High Power Laser Rifle",
    "High Power Plasma Rifle",
    "Heavy Plasma Shotgun",
    "Nuclear Plasma Revolver",
    "Flamethrower",
    "Rigelatin Assault Weapon",
    "Unmaker",
    "Hell's Reign",
    "Nuclear Onslaught",
    "Chameleon Rifle",
    "Suss Gun",
    "Plasma Redirection Cannon",
    "Lightweaver",
    "Railgun",
    "Combat Translocator",
    "Nuclear Plasma Rifle",
    "Nuclear Plasma Pistol",
    "Laser Rifle",
    "Plasma Shotgun",
    "Plasma Rifle",
    "Zeus Cannon",
    "Biggest Fucking Nuclear Gun",
    "Biggest Fucking Gun",
    "Nuclear VBFG9000",
    "VBFG9000",
    "High Power Nuclear BFG9000",
    "High Power BFG9000",
    "BFG Infinity",
    "Reality Distortion Array",
    "Baron Blaster",
    "Particle Beam Cannon",
    "Charch's Null Pointer",
    "BFG10K",
    "Nuclear BFG9000",
    "BFG9000"
  },

  { // High Noon Drifter
    "Nimurdal", "Heki",
    "R&C Thunderhawk",
    "Montaraz 1899", "Cintia 1901",
    "M-12 Grasa x2", "M-12 Grasa",
    "V45 Grenades",
    "Gate of Anthrakia",
    "Mask of Basilissa",
    "Bullwhips",
  },

  { // Freedoom
    "Angle Grinder", "Fists",
    "Handgun",
    "Double-barrelled Shotgun", "Pump-action Shotgun",
    "Minigun",
    "Missile Launcher",
    "Polaric Energy Cannon",
    "SKAG 1337",
  },

}; // end of printable names
