// Weapons data section ////////////////////////////////////////////////////////

#define SETS_NUMBER 50

#define SET_ABORT_M            4

#define SET_CYAN_DOOM         13
#define SET_REKKR             18

#define SET_BRUTAL_DOOM       28
#define SET_FALLBACK          29

#define SET_FREEDOOM          44
#define SET_X_WEAPON          45

// List of known weapon classes.
// When adding to this list, don't forget to increase SETS_NUMBER.
// If weapon mod has single weapon set shared by several player classes, there is
// no need to add them all here. Add only one, and the rest will go to
// WM_SpecialMatchClassToWeaponSet(str class) function.
str playerClassNames[SETS_NUMBER] =
{
  "wm_reserved",         //  0. [Reserved]
  "wm_reserved",         //  1. [Reserved]
  "EriPlayer",           //  2. Eriguns 1 - Standard weapons
  "AltPlayer",           //  3. Eriguns 1 - Extended weapons
  "DoomPlayer",          //  4. abort_m | reason: no player class
  "wm_reserved",         //  5. [Reserved]
  "FDPlutPlayer",        //  6. Final Doomer - Plutonia
  "FDTNTPlayer",         //  7. Final Doomer - TNT
  "FDDoom2Player",       //  8. Final Doomer - Doom 2
  "FDAliensPlayer",      //  9. Final Doomer - Ancient Aliens
  "FDJPCPPlayer",        // 10. Final Doomer - JPCP
  "FDBTSXPlayer",        // 11. Final Doomer - BTSX
  "FasPlayer",           // 12. Faspons
  "DoomPlayer",          // 13. Cyan-Doom  | reason: no player class
  "wm_reserved",         // 14. [Reserved]
  "ComplexDoomPlayer",   // 15. Complex Doom V27a3
  "wm_reserved",         // 16. [Reserved]
  "DoomMarine",          // 17. Hard-Doom v8.2f
  "DoomPlayer",          // 18. REKKR      | reason: Dehacked
  "ChexPlayer",          // 19. Chex Quest | reason: SSG is deathmatch-only
  "StrifePlayer",        // 20. Strife
  "ArgPlayer",           // 21. Argent (v0.5.3)
  "64DoomPlayer",        // 22. Doom 64 'weapons only' (updated 5-29-2016), Doom 64 Retribution 1.4a | reason: tags
  "DoomPlayerFixed",     // 23. Responsive Weapons + Faster Weapon Switching
  "Xplayer",             // 24. Dead Marine v0.9.3
  "wm_reserved",         // 25. [Reserved]
  "wm_reserved",         // 26. [Reserved]
  "wm_reserved",         // 27. [reserved]
  "BDoomer",             // 28. Brutal Doom - Rifle/Pistol Start, Tactical Mode | reason: secret weapons, shared set
  "m8f_wm_Fallback",     // 29. Fallback mode

  "wm_reserved",         // 30. [Reserved]
  "wm_reserved",         // 31. [Reserved]
  "wm_reserved",         // 32. [Reserved]
  "wm_reserved",         // 33. [Reserved]
  "wm_reserved",         // 34. [Reserved]

  "WWColaPlayer",        // 35. WW-Cola3
  "HexenColaPlayer",     // 36. WW-Cola3 - Hexen
  "Eilidh",              // 37. Netronian Chaos v3
  "SquarePlayer",        // 38. Adventures of Square, Ep 1-2
  "wm_reserved",         // 39. [Reserved]
  "msx_player",          // 40. Project MSX 0.2a
  "wm_reserved",         // 41. [Reserved]
  "wm_reserved",         // 42. [Reserved]
  "wm_reserved",         // 43. [Reserved]
  "DoomPlayer",          // 44. Freedoom                     | reason: weapon tags, SSG in Doom 1
  "XDoomPlayer",         // 45. X-Weapon                     | reason: weapon upgrades, shared set
  "wm_reserved",         // 46. [Reserved]
  "wm_reserved",         // 47. [Reserved]
  "wm_reserved",         // 48. [Reserved]

  "FTPlayer",            // 49. Factotum [010618]            | reason: weapon upgrades
};

// List of weapon counts for every known weapon mod.
// Must include all weapons.
// Maximal supported weapon count is MAX_WEAPONS_NUMBER.
int weaponCounts[SETS_NUMBER] =
{
  0,  // [Reserved]
  0,  // [Reserved]
  9, 13, // Eriguns 1
  11, // abort_m
  0,  // [Reserved]
  9, 9, 9, 9, 8, 9, // Final Doomer: Plutonia, TNT, Doom2, AA, JPCP, BTSX
  9,  // Faspons
  16, // Cyan-Doom
  0,  // [Reserved]
  18, // Complex Doom
  0,  // [Reserved]
  14, // Hard-Doom
  8,  // REKKR
  9,  // Chex Quest
  11, // Strife
  11, // Argent
  16, // Doom 64 X
  9,  // Responsive Weapons + Faster Weapon Switching
  9,  // Dead Marine
  0,  // [Reserved]
  0,  // [Reserved]
  0,  // [Reserved]
  22, // Brutal Doom
  0,  // [Reserved]
  0,  // [Reserved]
  0,  // [Reserved]
  0,  // [Reserved]
  0,  // [Reserved]
  0,  // [Reserved]
  8,  // WW-Cola3
  8,  // WW-Cola3 - Hexen
  24, // Netronian Chaos
  10, // Adventures of Square
  0,  // [Reserved]
  8,  // Project MSX
  0,  // [Reserved]
  0,  // [Reserved]
  0,  // [Reserved]
  9,  // Freedoom
  29, // X-Weapon
  0,  // [Reserved]
  0,  // [Reserved]
  0,  // [Reserved]
  11, // Factotum
};

// List of corresponding weapon slots.
// Number of slots in weapon set must be equal to weapon count in weaponCounts
// array.
int slots[SETS_NUMBER][MAX_WEAPONS_NUMBER] =
{
  { }, // Reserved
  { }, // Reserved

  // Eriguns
  { 1, 1, 2, 3, 3, 4, 5, 6, 7 },
  { 1, 1, 2, 3, 3, 3, 4, 4, 5, 5, 6, 7, 8 },

  { 1, 1, 2, 3, 3, 4, 5, 6, 7, 7, 8 }, // abort_m

  { }, // Reserved

  // Final Doomer
  { 1, 1, 2, 3, 3, 4, 5, 6, 7 },
  { 1, 1, 2, 3, 3, 4, 5, 6, 7 },
  { 1, 1, 2, 3, 3, 4, 5, 6, 7 },
  { 1, 1, 2, 3, 3, 4, 5, 6, 7 },
  { 1, 2, 3, 3, 4, 5, 6, 7 },
  { 1, 1, 2, 3, 3, 4, 5, 6, 7 },

  { 1, 1, 2, 3, 3, 4, 5, 6, 7 }, // Faspons

  { 1, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8 }, // Cyan-Doom

  { }, // Reserved

  { // Complex Doom
    1, 1,
    2,
    3, 3, 3, 3,
    4, 4,
    5, 5,
    6, 6, 6,
    7, 7, 7,
    8,
  },

  { }, // Reserved

  { 1, 1, 2, 3, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7 }, // Hard-Doom

  { 1, 1, 2, 3, 4, 5, 6, 7 }, // REKKR

  { 1, 1, 2, 3, 3, 4, 5, 6, 7 }, // Chex Quest

  { 1, 2, 2, 3, 4, 5, 5, 6, 7, 7, 8 }, // Strife

  { 1, 1, 2, 3, 3, 4, 4, 5, 6, 6, 7 }, // Argent

  { 1, 1, 2, 2, 3, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8 }, // Doom 64

  { 1, 1, 2, 3, 3, 4, 5, 6, 7 }, // Responsive Weapons + Faster Weapon Switching

  { 1, 1, 2, 3, 3, 4, 5, 6, 7 }, // Dead Marine

  { }, // Reserved
  { }, // Reserved
  { }, // Reserved

  { 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5, 6, 6, 7, 7, 7, 8, 8 }, // Brutal

  { }, // Reserved
  { }, // Reserved
  { }, // Reserved
  { }, // Reserved
  { }, // Reserved
  { }, // Reserved

  { 1, 2, 2, 3, 4, 5, 6, 7 }, // WW-Cola3
  { 1, 2, 2, 3, 4, 5, 6, 7 }, // WW-Cola3 - Hexen

  { // Netronian Chaos
    1, 1, 1,
    2, 2, 2,
    3, 3, 3,
    4, 4, 4,
    5, 5, 5,
    6, 6, 6,
    7, 7, 7,
    8, 8, 8
  },

  { 1, 1, 2, 2, 3, 3, 4, 5, 6, 7 }, // Adventures of Square

  { }, // Reserved

  { 1, 2, 3, 4, 5, 6, 7, 8 }, // Project MSX

  { }, // Reserved
  { }, // Reserved
  { }, // Reserved

  { 1, 1, 2, 3, 3, 4, 5, 6, 7 }, // Freedoom

  { // X-Weapon
    1,
    2, 2, 2, 2,
    3, 3, 3, 3,
    4, 4, 4,
    5, 5, 5,
    6, 6, 6,
    7, 7, 7,
    8, 8, 8, 8,
    9, 9,
    0, 0,
  },

  { }, // Reserved
  { }, // Reserved
  { }, // Reserved

  { 1, 2, 2, 3, 4, 5, 5, 6, 7, 8, 9 }, // Factotum

};

// List of weapon classes.
// Number of classes here must be equal to weapon count in weaponCounts array.
str names[SETS_NUMBER][MAX_WEAPONS_NUMBER] =
{
  { }, // Reserved
  { }, // Reserved

  { // Eriguns 1
    "EriChainsaw", "EriFist",
    "EriPistol",
    "EriSuperShotgun",
    "EriShotgun",
    "EriMachinegun",
    "EriRocketLauncher",
    "EriPlasmaRifle",
    "EriBFG9000"
  },
  {
    "EriChainsaw", "EriFist",
    "AltPistol",
    "EriAutoShotgun", "AltSuperShotgun", "EriShotgun",
    "EriGatlingGun", "EriMachinegun",
    "EriMissileLauncher", "EriRocketLauncher",
    "EriPlasmaRifle",
    "EriBFG9000",
    "EriGrenadeLauncher"
  },

  { // abort_m
    "TileWeapon", "FingerPoke",
    "PeaShooter",
    "GunShotgun", "BoxOfPellets",
    "BigPee",
    "Lewd",
    "AstolfoWeapon",
    "ToolTim", "OuchWeapon",
    "AbortButton"
  },

  { }, // Reserved

  {
    "FDPlutChainsaw", "FDPlutFist",
    "FDPlutPistol",
    "FDPlutSuperShotgun", "FDPlutShotgun",
    "FDPlutChaingun",
    "FDPlutRocketLauncher",
    "FDPlutPlasmaRifle",
    "FDPlutBFG9000"
  },
  {
    "FDTNTChainsaw", "FDTNTFist",
    "FDTNTPistol",
    "FDTNTSuperShotgun", "FDTNTShotgun",
    "FDTNTChaingun",
    "FDTNTRocketLauncher",
    "FDTNTPlasmaRifle",
    "FDTNTBFG9000"
  },
  {
    "FDDoom2Chainsaw", "FDDoom2Fist",
    "FDDoom2Pistol",
    "FDDoom2SuperShotgun", "FDDoom2Shotgun",
    "FDDoom2Chaingun",
    "FDDoom2RocketLauncher",
    "FDDoom2PlasmaRifle",
    "FDDoom2BFG9000"
  },
  {
    "FDAliensChainsaw", "FDAliensFist",
    "FDAliensPistol",
    "FDAliensSuperShotgun", "FDAliensShotgun",
    "FDAliensChaingun",
    "FDAliensRocketLauncher",
    "FDAliensPlasmaRifle",
    "FDAliensBFG9000"
  },
  {
    "FDJPCPFist",
    "FDJPCPPistol",
    "FDJPCPSuperShotgun", "FDJPCPShotgun",
    "FDJPCPChaingun",
    "FDJPCPRocketLauncher",
    "FDJPCPPlasmaRifle",
    "FDJPCPBFG9000"
  },
  {
    "FDBTSXChainsaw", "FDBTSXFist",
    "FDBTSXPistol",
    "FDBTSXSuperShotgun", "FDBTSXShotgun",
    "FDBTSXChaingun",
    "FDBTSXRocketLauncher",
    "FDBTSXPlasmaRifle",
    "FDBTSXBFG9000"
  },

  { // Faspons
    "Motorsaw", "Knuckles",
    "CombatRifle",
    "DoubleBarrel", "Riotgun",
    "Minigun",
    "RPG",
    "PulseRifle",
    "BFG"
  },

  { // Cyan-Doom
    "Magnetsaw", "Chainsaw", "Fist",
    "Rifle", "Pistol",
    "SuperShotgun", "Shotgun",
    "STMinigun", "Chaingun",
    "STGrenadeLauncher", "RocketLauncher",
    "STRailgun", "PlasmaRifle",
    "STBFG10K", "BFG9000",
    "SkullStaff"
  },

  { }, // Reserved

  { // Complex Doom
    "Chainsaw ", "Melee",
    "Handgun",
    "Quad Barrel Shotgun", "Double Barrel Shotgun", "Assault Shotgun", "Combat Shotgun",
    "Minigun ", "Assault Rifle",
    "Grenade Launcher", "Rocket Launcher",
    "Railgun ", "Demon Tech Rifle", "Plasma Rifle",
    "Demon Tech BFG10K", "BFG10K ", "BFG9500",
    "MP40",
  },

  { }, // Reserved

  { // Hard-Doom
    "Chainsaw~", "Fist~",
    "Pistol~",
    "Quad-Shotgun", "SuperShotgun~", "Shotgun~",
    "Minigun~", "Chaingun~",
    "GrenadeLauncher~", "RocketLauncher~",
    "PlasmaRifle~", "Sonic Railgun",
    "BFG10K~", "BFG9000~",
  },

  { // REKKR
    "Chainsaw", "Fist",
    "Pistol",
    "Shotgun",
    "Chaingun",
    "RocketLauncher",
    "PlasmaRifle",
    "BFG9000"
  },

  { // Chex Quest
    "SuperBootspork", "Bootspoon",
    "MiniZorcher",
    "SuperLargeZorcher", "LargeZorcher",
    "RapidZorcher",
    "ZorchPropulsor",
    "PhasingZorcher",
    "LAZDevice",
  },

  { // Strife
    "PunchDagger",
    "StrifeCrossbow", "StrifeCrossbow2",
    "AssaultGun",
    "MiniMissileLauncher",
    "StrifeGrenadeLauncher", "StrifeGrenadeLauncher2",
    "FlameThrower",
    "Mauler", "Mauler2",
    "Sigil"
  },

  { // Argent
    "ArgChainsaw",
    "ArgFist",
    "ArgPistol",
    "ArgSuperShotgun",
    "ArgShotgun",
    "ArgChaingun",
    "ArgHeavyAR",
    "ArgRocketLauncher",
    "ArgGaussCannon",
    "ArgPlasmaRifle",
    "ArgBFG9000",
  },

  { // Doom 64
    "64Chainsaw", "64Fist",
    "64Uzi", "64Pistol",
    "64Devastator", "64SuperShotgun", "64Shotgun",
    "64Nailgun", "64Chaingun",
    "64Flamethrower", "64RocketLauncher",
    "64Railgun", "64PlasmaRifle",
    "Unmaker", "64BFG9000",
    "64Unmaker",
  },

  { // Responsive Weapons + Faster Weapon Switching
    "ChainsawFixed", "FistFixed",
    "PistolFixed",
    "SuperShotgunFixed", "ShotgunFixed",
    "ChaingunFixed",
    "RocketLauncherFixed",
    "PlasmaRifleFixed",
    "BFG9000Fixed"
  },

  { // Dead Marine
    "XtremeSaw", "Xtremefist",
    "XtremePistol",
    "XtremeSSG", "XtremeShotgun",
    "XtremeChaingun",
    "XtremeRLauncher",
    "XtremePlasma",
    "XtremeBFG"
  },

  { }, // Reserved
  { }, // Reserved
  { }, // Reserved

  { // Brutal Doom
    "Melee_Attacks", "Chain_saw", "BrutalAxe",
    "MP40", "BrutalSMG", "BrutalPistol",
    "SSG", "Shot_Gun", "AssaultShotgun",
    "HitlersBuzzsaw", "Minigun", "Rifle", "Machinegun",
    "Rocket_Launcher", "GrenadeLauncher",
    "Plasma_Gun", "Railgun",
    "BIG_FUCKING_GUN", "Unmaker", "BFG10k",
    "FlameCannon", "HellishMissileLauncher"
  },

  { }, // Reserved
  { }, // Reserved
  { }, // Reserved
  { }, // Reserved
  { }, // Reserved
  { }, // Reserved

  { // WW-Cola3
    "ColaHandgun",
    "PumpShotgun", "DualPumpShotgun",
    "CardThrower",
    "PlasmaAutorifle",
    "MissileLauncher",
    "Piledriver",
    "ToothpasteLaser",
  },
  { // WW-Cola3
    "ColaHandgun",
    "PumpShotgun", "DualPumpShotgun",
    "CardThrower",
    "PlasmaAutorifle",
    "MissileLauncher",
    "Piledriver",
    "ToothpasteLaser",
  },

  { // Netronian Chaos
    "LB1000PileBanger", "AnaikaDagger", "M101Blade",
    "EG10HeavyPistol", "V57BurstPistol", "V96ServicePistol",
    "FASR33AssaultSupporter", "VS4Sweeper", "VS2Riotgun",
    "PAG20PDW", "V80BSMG", "V88Carbine",
    "VARACarbine", "AG100Machinegun", "V74ARifle",
    "M12FMGR", "V32AARifle", "V50MLauncher",
    "M189Auto", "V99AThrower", "VE1Coilgun",
    "HeavyBarrel", "VM201TD", "Ver110VC"
  },

  { // Adventures of Square
    "PaintGuns", "PaintGun",
    "Oozis", "Oozi",
    "Quadcannon", "Shotbow",
    "PaintCannon",
    "HellShellLauncher",
    "Sceptre",
    "Defibrillator"
  },

  { }, // Reserved

  { // Project MSX
    "RegularFists",
    "golampistol",
    "hydrashotgun",
    "barracudarifle",
    "raptorshotgun",
    "tauruscannon",
    "chimerarifle",
    "orionSniper"
  },

  { }, // Reserved
  { }, // Reserved
  { }, // Reserved

  { // Freedoom
    "Chainsaw", "Fist",
    "Pistol",
    "SuperShotgun", "Shotgun",
    "Chaingun",
    "RocketLauncher",
    "PlasmaRifle",
    "BFG9000"
  },

  { // X-Weapon
    "FistX",

    "XPistolXX",
    "SPistolX",
    "BFDPistolX",
    "PistolX",

    "HavokCannon",
    "XShotgunX",
    "SShotgunX",
    "ShotgunX",

    "XAssaultRifleX",
    "SAssaultRifleX",
    "AssaultRifleX",

    "XSuperShotgunX",
    "SSuperShotgunX",
    "SuperShotgunX",

    "XPhaseLauncherX",
    "SPhaseLauncherX",
    "PhaseLauncherX",

    "XPlasmaRifleX",
    "SDemontechRifleX",
    "DemontechRifleX",

    "XBFSGX",
    "XBFGGX",
    "SBFGX",
    "BFGX",

    "GrenadeCannonX",
    "ChaingunX",

    "DPistolX",
    "XPistolX",
  },

  { }, // Reserved
  { }, // Reserved
  { }, // Reserved

  { // Factotum
    "FKMachete",
    "FKPistol", "FKPistolUP",
    "FKShotgun",
    "FKMachinegun",
    "FKLauncher", "FKLauncherUP",
    "FKPlasmaRifle",
    "FKCarbine",
    "FKHoser",
    "FKGrenades",
  },

}; // end of actor/class names /////////////////////////////////////////////////

// List of weapon names (tags).
// Number of names here must be equal to weapon count in weaponCounts array.
str tags[SETS_NUMBER][MAX_WEAPONS_NUMBER] =
{
  { }, // Reserved
  { }, // Reserved

  { // Eriguns
    "Chainsaw", "Fist",
    "Pistol",
    "Super Shotgun", "Shotgun",
    "Chaingun",
    "Rocket Launcher",
    "Plasma Rifle",
    "BFG9000"
  },
  {
    "Chainsaw", "Fist",
    "Pistol",
    "Auto Shotgun", "Super Shotgun", "Shotgun",
    "Gatling Gun", "Machinegun",
    "Missile Launcher", "Rocket Launcher",
    "Plasma Rifle",
    "BFG9000",
    "Grenade Launcher"
  },

  { // abort_m
    "Floor Tile", "Finger poke",
    "Pea shooter",
    "Gunshotgun", "Pellet Box",
    "Big P",
    "Assblaster",
    "Astolfo plush",
    "Tim Allen", "Ouch Face",
    "Abort button"
  },

  { }, // Reserved

  { // Final Doomer
    "Power Saw", "Melee",
    "Ol' Faithful",
    "Super Shotgun", "Scoped Shotgun",
    "Machine Gun",
    "Grenade Launcher",
    "Heavy Machine Gun",
    "Quantum Accelerator"
  },
  {
    "Halderman Device", "Melee",
    "Prototype Pistol",
    "Burst Shotgun", "Tactical Shotgun",
    "Dual Uzis",
    "Missile Launcher",
    "Maser",
    "Incursion Annihilator"
  },
  {
    "Chainsaw", "Melee",
    "Pistol",
    "Super Shotgun", "Shotgun",
    "Chaingun",
    "Rocket Launcher",
    "Plasma Rifle",
    "BFG 9000"
  },
  {
    "Stasis Bow", "Trench Knife",
    "Ancient Pistol",
    "Hybrid SSG", "Ancient Shotgun",
    "Ancient AK",
    "Photon Scepter",
    "Alien Elite Weapon",
    "Illuminator"
  },
  {
    "Katana",
    "Silenced Pistol",
    "Neutron Cascader", "Neutron Pulser",
    "Burst Needler",
    "Prism Cannon",
    "Ofuda Caster",
    "Onmyou Devastator"
  },
  {
    "NanoCore", "Power Fist",
    "Charge Pistol",
    "Machreaper", "Arc Blaster",
    "Pulse Rifle",
    "Pulse Cannon",
    "Plasma Vulcan",
    "X-Spark Cannon"
  },

  { // Faspons
    "Chainsaw", "Knuckles",
    "Combat Rifle",
    "Double Barrel Shotgun", "Riotgun",
    "Minigun",
    "RPG",
    "Pulse Rifle",
    "BFG9000"
  },

  { // Cyan-Doom
    "Super Chainsaw", "Chainsaw", "Brass Knuckles",
    "Rifle", "Pistol",
    "Super Shotgun", "Shotgun",
    "Minigun", "Chaingun",
    "Grenade Launcher", "Rocket Launcher",
    "Railgun", "Plasma Rifle",
    "BFG10K", "BFG 9000",
    "Skull Staff",
  },

  { }, // Reserved

  { // Complex Doom
    "Chainsaw", "Melee",
    "Handgun",
    "Quad Barrel Shotgun", "Double Barrel Shotgun", "Assault Shotgun", "Combat Shotgun",
    "Minigun", "Assault Rifle",
    "Grenade Launcher", "Rocket Launcher",
    "Railgun", "Demon Tech Rifle", "Plasma Rifle",
    "Demon Tech BFG10K", "BFG10K", "BFG9500",
    "MP40",
  },

  { }, // Reserved

  { // Hard-Doom
    "Chainsaw", "Fist",
    "Pistol",
    "Quad-Shotgun", "Super Shotgun", "Shotgun",
    "Minigun", "Chaingun",
    "Grenade Launcher", "Rocket Launcher",
    "Plasma Rifle", "Sonic Railgun",
    "BFG10K", "BFG9000",
  },

  { // REKKR
    "Axe", "Fists",
    "Soul Bow",
    "Steelshot Launcher",
    "Soul Launcher",
    "Runic Staff",
    "Holy Relic",
    "Blessing of the Gods"
  },

  { // Chex Quest
    "Super Bootspork", "Spoon",
    "Mini Zorcher",
    "Super-Large Zorcher", "Large Zorcher",
    "Rapid Zorcher",
    "Zorch Propulsor",
    "Phasing Zorcher",
    "LAZ Device",
  },

  { // Strife
    "Dagger",
    "Crossbow: Electric Bolts",
    "Crossbow: Poison Bolts",
    "Assault Gun",
    "Mini Missile Launcher",
    "Grenade Launcher: HE",
    "Grenade Launcher: Phosphorus",
    "Flame Thrower",
    "Mauler: Scatter",
    "Mauler: Torpedo",
    "SIGIL"
  },

  { // Argent
    "Chainsaw",
    "Fists",
    "Pistol",
    "Super Shotgun",
    "Combat Shotgun",
    "Chaingun",
    "Heavy Assault Rifle",
    "Rocket Launcher",
    "Gauss Cannon",
    "Plasma Rifle",
    "BFG 9000",
  },

  { // Doom 64
    "Chainsaw", "Fist",
    "Uzi", "Pistol",
    "Devastator", "Super Shotgun", "Shotgun",
    "Nailgun", "Chaingun",
    "Flamethrower", "Rocket Launcher",
    "Railgun", "Plasma Rifle",
    "Unmaker", "BFG 9000",
    "Unmaker",
  },

  { // Responsive Weapons + Faster Weapon Switching
    "Chainsaw", "Brass Knuckles",
    "Pistol",
    "Super Shotgun", "Shotgun",
    "Chaingun",
    "Rocket Launcher",
    "Plasma Rifle",
    "BFG 9000"
  },

  { // Dead Marine
    "Chainsaw", "Brass Knuckles",
    "Pistol",
    "Super Shotgun", "Shotgun",
    "Chaingun",
    "Rocket Launcher",
    "Plasma Rifle",
    "BFG 9000"
  },

  { }, // Reserved
  { }, // Reserved
  { }, // Reserved

  { // Brutal Doom
    "Melee", "Chainsaw", "Axe",
    "MP40", "SMG", "Pistol",
    "SSG", "Shotgun", "AA-12 Assault Shotgun",
    "Hitler's Buzzsaw", "Minigun", "Assault Rifle", "Machine Gun",
    "Rocket Launcher", "Grenade Launcher",
    "Plasma Gun", "Railgun",
    "BFG-9000", "Unmaker", "BFG10K",
    "Flame Cannon", "Hellish Missile Launcher"
  },

  { }, // Reserved
  { }, // Reserved
  { }, // Reserved
  { }, // Reserved
  { }, // Reserved
  { }, // Reserved

  { // WW-Cola3
    "Marston R-1 Techvolver",
    "KS-23 Shotgun", "Dual KS-23 Shotguns",
    "Kare Brand Cards",
    "Plasma Autorifle",
    "Sidewinder Missile Launcher",
    "Piledriver",
    "Toothpaste Laser",
  },
  { // WW-Cola3
    "Marston R-1 Techvolver",
    "KS-23 Shotgun", "Dual KS-23 Shotguns",
    "Kare Brand Cards",
    "Plasma Autorifle",
    "Sidewinder Missile Launcher",
    "Piledriver",
    "Toothpaste Laser",
  },

  { // Netronian Chaos
    "Pile Banger Glove", "Anaika Hunting Daggers", "Digitalblade",
    "Heavy Caliber Pistol", "Burst Pistol", "Service Pistol",
    "Assault Supporter", "Hand Sweeper", "Riotgun",
    "Personal Defence Arm", "Burst SMG", "Machine Carbine",
    "Semi Auto Rifle", "Squad Support Gun", "Combat Rifle",
    "Cyro Grenade Bouncer", "Anti Armor Rifle", "Missile Launcher",
    "Full Auto LAWF", "Personal Annihilator", "Semi Coil Carbine",
    "Fierce Caliber", "Tri Desolator", "Heavy Vulcan"
  },

  { // Adventures of Square
    "Dual Paint Guns", "Paint Gun",
    "Dual Oozis", "Oozi",
    "Quad Cannon", "Shotbow",
    "Paintgun Cannon",
    "Hellshell Launcher",
    "Cresceptre",
    "Defibrillator"
  },

  { }, // Reserved

  { // Project MSX
    "Fists",
    "Golam Pistol",
    "Hydra Shotgun",
    "Barracuda Rifle",
    "Raptor NailShotgun",
    "Taurus AutoCannon",
    "Chimaera Pulse Rifle",
    "Orion Gauss Cannon"
  },

  { }, // Reserved
  { }, // Reserved
  { }, // Reserved

  { // Freedoom
    "Angle Grinder", "Fists",
    "Handgun",
    "Double-barrelled Shotgun", "Pump-action Shotgun",
    "Minigun",
    "Missile Launcher",
    "Polaric Energy Cannon",
    "SKAG 1337",
  },

  { // X-Weapon
    "Fist", // 0

    "Magnum Handcannon", // 1
    "Nighthawk", // 2 upgraded
    "Bluetail Pistol", // 3
    "Nighthawk", // 4

    "Havok Cannon", // 5
    "Tactical Shotgun", // 6
    "Shotgun", // 7 upgrade
    "Shotgun", // 8

    "Legion Light Rifle", // 9
    "Upgraded Assault Rifle", // 10 upgrade?
    "Assault Rifle", // 11

    "Automatic Shotgun", // 12
    "Quadruple Barreled Shotgun", // 13 upgrade
    "Double Barreled Shotgun", // 14

    "Cluster Torpedo Launcher", // 15
    "Phasic Cluster Launcher", // 16 upgrade
    "Phasic Cluster Launcher", // 17

    "Dual Neutron Disruptor", // 18
    "Demontech Rifle", // 19 upgrade
    "Demontech Rifle", // 20

    "BFSG", // 21
    "BFGG", // 22
    "BFG", // 23 upgrade
    "BFG", // 24

    "Grenade Cannon", // 25
    "Chaingun", // 26

    "Fatman Pistol", // 27
    "Bluetail pistol", // 28
  },

  { }, // Reserved
  { }, // Reserved
  { }, // Reserved

  { // Factotum
    "Machete",
    "Beretta 92FS", "Upgraded Beretta 92",
    "Franchi SPAS-12",
    "Calico M950",
    "Springfield M79", "Upgraded M79",
    "Plasma Cannon",
    "Colt M4A1",
    "FNH M249",
    "Grenades",
  },

}; // end of printable names

// used in fallback mode
int priority[MAX_WEAPONS_NUMBER];
