// Weapons data section ////////////////////////////////////////////////////////

#define SETS_NUMBER  55

#define SET_VANILLA            0
#define SET_PERK               1
#define SET_ABORT_M            4

#define SET_CYAN_DOOM         13
#define SET_KRIEGSLAND        14
#define SET_WEAPONS_OF_SATURN 16
#define SET_REKKR             18
#define SET_CHEX_QUEST        19
#define SET_DOOM_64           22

#define SET_PARKOUR           25
#define SET_VSMOOTH           26

#define SET_BRUTAL_DOOM       28
#define SET_FALLBACK          29

#define SET_ACCESSORIES       41
#define SET_DOOMRL_ARSENAL    42
#define SET_HIGH_NOON_DRIFTER 43
#define SET_FREEDOOM          44
#define SET_X_WEAPON          45
#define SET_HARMONY           46
#define SET_DOOM_DELTA        47
#define SET_EVP               48
#define SET_FACTOTUM          49
#define SET_FLAKES_DOOM       50
#define SET_GUNCASTER_HERETIC 51
#define SET_GUNCASTER_DOOM    52
#define SET_GUNCASTER_HEXEN   53
#define SET_GUNCASTER_STRIFE  54

// List of known weapon classes.
// When adding to this list, don't forget to increase SETS_NUMBER.
// If weapon mod has single weapon set shared by several player classes, there is
// no need to add them all here. Add only one, and the rest will go to
// WM_SpecialMatchClassToWeaponSet(str class) function.
str playerClassNames[SETS_NUMBER] =
{
  "DoomPlayer",          //  0. Standard (Vanilla) | reason: SSG must be hidden in Doom 1
  "PerkDPlayer",         //  1. PerK's Smoother Weapon Animations Enhanced, Smooth Doom (2018-01-13) | hidden rifle.
  "EriPlayer",           //  2. Eriguns 1 - Standard weapons
  "AltPlayer",           //  3. Eriguns 1 - Extended weapons
  "DoomPlayer",          //  4. abort_m | reason: no player class
  "BD_DoomPlayer",       //  5. Beautiful Doom
  "FDPlutPlayer",        //  6. Final Doomer - Plutonia
  "FDTNTPlayer",         //  7. Final Doomer - TNT
  "FDDoom2Player",       //  8. Final Doomer - Doom 2
  "FDAliensPlayer",      //  9. Final Doomer - Ancient Aliens
  "FDJPCPPlayer",        // 10. Final Doomer - JPCP
  "FDBTSXPlayer",        // 11. Final Doomer - BTSX
  "FasPlayer",           // 12. Faspons
  "DoomPlayer",          // 13. Cyan-Doom  | reason: no player class
  "FKPlayer",            // 14. Kriegsland | reason: class shared with Flakes Doom
  "ComplexDoomPlayer",   // 15. Complex Doom V27a3
  "SaturnPlayer",        // 16. Weapons of Saturn May 09, 2018 | reason: forbid weapon holstering
  "DoomMarine",          // 17. Hard-Doom v8.2f
  "DoomPlayer",          // 18. REKKR      | reason: Dehacked
  "ChexPlayer",          // 19. Chex Quest | reason: SSG is deathmatch-only
  "StrifePlayer",        // 20. Strife
  "ArgPlayer",           // 21. Argent (v0.5.3)
  "64DoomPlayer",        // 22. Doom 64 'weapons only' (updated 5-29-2016), Doom 64 Retribution 1.4a | reason: tags
  "DoomPlayerFixed",     // 23. Responsive Weapons + Faster Weapon Switching
  "Xplayer",             // 24. Dead Marine v0.9.3
  "ParkourPlayer",       // 25. Parkour v1.1 | reason: secret weapons
  "PerkDPlayer",         // 26. VSmooth (Vanilla doom smooth weapons) | reason: Dehacked except 1 class
  "[reserved]",          // 27. [reserved]
  "BDoomer",             // 28. Brutal Doom - Rifle/Pistol Start, Tactical Mode | reason: secret weapons, shared set
  "m8f_wm_Fallback",     // 29. Fallback mode
  "wm_reserved",         // 30. [Reserved]
  "wm_reserved",         // 31. [Reserved]

  "Trailblazer_Doom",    // 32. Trailblazer v1.4b - Doom
  "Trailblazer_Heretic", // 33. Trailblazer v1.4b - Heretic
  "Trailblazer_Hexen",   // 34. Trailblazer v1.4b - Hexen

  "WWColaPlayer",        // 35. WW-Cola3
  "HexenColaPlayer",     // 36. WW-Cola3 - Hexen
  "Eilidh",              // 37. Netronian Chaos v3
  "SquarePlayer",        // 38. Adventures of Square, Ep 1-2
  "[reserved]",          // 39. [Reserved]
  "msx_player",          // 40. Project MSX 0.2a
  "DoomNukem",           // 41. Accessories to Murder        | reason: secret weapons
  "DoomRLMarine",        // 42. DoomRL Arsenal 1.05          | reason: all weapons are secret, shared set
  "WesternPlayer",       // 43. High Noon Drifter v1.2c      | reason: double SMG, double wips
  "DoomPlayer",          // 44. Freedoom                     | reason: weapon tags, SSG in Doom 1
  "XDoomPlayer",         // 45. X-Weapon                     | reason: weapon upgrades, shared set
  "DoomPlayer",          // 46. Harmony                      | reason: Dehacked
  "ThiPlayer",           // 47. Doom Delta v2.0 (11-2-2017)  | reason: secret weapon
  "PerkDPlayer",         // 48. EVP v17                      | reason: class shared with Smooth Doom

  "FTPlayer",            // 49. Factotum [010618]            | reason: weapon upgrades
  "FKPlayer",            // 50. Flakes Doom v2.6b (06/03/18) | reason: hidden weapon in games

  "Guncaster",           // 51. Guncaster - Heretic | v3.1
  "GuncasterDoom",       // 52. Guncaster - Doom    | reason: weapons from all
  "GuncasterHexen",      // 53. Guncaster - Hexen   | games get into the list.
  "GuncasterStrife",     // 54. Guncaster - Strife  |

};

// List of weapon counts for every known weapon mod.
// Must include all weapons.
// Maximal supported weapon count is MAX_WEAPONS_NUMBER.
int weaponCounts[SETS_NUMBER] =
{
  9,  // Standard
  10, // PerK's Smoother Weapon Animations Enhanced + Smooth Doom
  9, 13, // Eriguns 1
  11, // abort_m
  9,  // Beautiful Doom
  9, 9, 9, 9, 8, 9, // Final Doomer: Plutonia, TNT, Doom2, AA, JPCP, BTSX
  9,  // Faspons
  16, // Cyan-Doom
  22 + 5, // Kriegsland
  18, // Complex Doom
  12, // Weapons of Saturn
  14, // Hard-Doom
  8,  // REKKR
  9,  // Chex Quest
  11, // Strife
  11, // Argent
  16, // Doom 64 X
  9,  // Responsive Weapons + Faster Weapon Switching
  9,  // Dead Marine
  12, // Parkour
  9,  // VSmooth
  0,  // [Reserved]
  22, // Brutal Doom
  0,  // [Reserved]
  0,  // [Reserved]
  0,  // [Reserved]
  12, // Trailblazer - Doom
  12, // Trailblazer - Heretic
  12, // Trailblazer - Hexen
  8,  // WW-Cola3
  8,  // WW-Cola3 - Hexen
  24, // Netronian Chaos
  10, // Adventures of Square
  0,  // [Reserved]
  8,  // Project MSX
  10, // Accessories to Murder
  217, // DoomRL Arsenal
  11, // High Noon Drifter
  9,  // Freedoom
  29, // X-Weapon
  6,  // Harmony
  13, // Doom Delta
  9,  // EVP
  11, // Factotum
  19, // Flakes Doom

  10, // Guncaster + Addon : Heretic
  11, // Guncaster + Addon : Doom
  11, // Guncaster + Addon : Hexen
  11, // Guncaster + Addon : Strife
};

// List of corresponding weapon slots.
// Number of slots in weapon set must be equal to weapon count in weaponCounts
// array.
int slots[SETS_NUMBER][MAX_WEAPONS_NUMBER] =
{
  { 1, 1, 2, 3, 3, 4, 5, 6, 7 }, // Standard

  // PerK's Smoother Weapon Animations Enhanced + Smooth Doom
  { 1, 1, 2, 2, 3, 3, 4, 5, 6, 7 },

  // Eriguns
  { 1, 1, 2, 3, 3, 4, 5, 6, 7 },
  { 1, 1, 2, 3, 3, 3, 4, 4, 5, 5, 6, 7, 8 },

  { 1, 1, 2, 3, 3, 4, 5, 6, 7, 7, 8 }, // abort_m

  { 1, 1, 2, 3, 3, 4, 5, 6, 7 }, // Beautiful Doom

  // Final Doomer
  { 1, 1, 2, 3, 3, 4, 5, 6, 7 },
  { 1, 1, 2, 3, 3, 4, 5, 6, 7 },
  { 1, 1, 2, 3, 3, 4, 5, 6, 7 },
  { 1, 1, 2, 3, 3, 4, 5, 6, 7 },
  { 1, 2, 3, 3, 4, 5, 6, 7 },
  { 1, 1, 2, 3, 3, 4, 5, 6, 7 },

  { 1, 1, 2, 3, 3, 4, 5, 6, 7 }, // Faspons

  { 1, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8 }, // Cyan-Doom

  { // Kriegsland
    1, 1, 1,
    2, 2, 2,
    3, 3,
    4, 4,
    5, 5, 5,
    6, 6, 6,
    7, 7, 7,
    8, 8, 8,
    9, 9, 9, 9, 9, // cross akimbos
  },

  { // Complex Doom
    1, 1,
    2,
    3, 3, 3, 3,
    4, 4,
    5, 5,
    6, 6, 6,
    7, 7, 7,
    8,
  },

  { 1, 1, 2, 2, 2, 3, 3, 4, 4, 5, 6, 7 }, // Weapons of Saturn

  { 1, 1, 2, 3, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7 }, // Hard-Doom

  { 1, 1, 2, 3, 4, 5, 6, 7 }, // REKKR

  { 1, 1, 2, 3, 3, 4, 5, 6, 7 }, // Chex Quest

  { 1, 2, 2, 3, 4, 5, 5, 6, 7, 7, 8 }, // Strife

  { 1, 1, 2, 3, 3, 4, 4, 5, 6, 6, 7 }, // Argent

  { 1, 1, 2, 2, 3, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8 }, // Doom 64

  { 1, 1, 2, 3, 3, 4, 5, 6, 7 }, // Responsive Weapons + Faster Weapon Switching

  { 1, 1, 2, 3, 3, 4, 5, 6, 7 }, // Dead Marine

  { 1, 1, 2, 2, 3, 3, 4, 5, 6, 7, 8, 9 }, // Parkour

  { 1, 1, 2, 3, 3, 4, 5, 6, 7 }, // VSmooth

  { }, // Reserved

  { 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5, 6, 6, 7, 7, 7, 8, 8 }, // Brutal

  { }, // Reserved
  { }, // Reserved
  { }, // Reserved

  { 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 7 }, // Trailblazer
  { 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 7 },
  { 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 7 },

  { 1, 2, 2, 3, 4, 5, 6, 7 }, // WW-Cola3
  { 1, 2, 2, 3, 4, 5, 6, 7 }, // WW-Cola3 - Hexen

  { // Netronian Chaos
    1, 1, 1,
    2, 2, 2,
    3, 3, 3,
    4, 4, 4,
    5, 5, 5,
    6, 6, 6,
    7, 7, 7,
    8, 8, 8
  },

  { 1, 1, 2, 2, 3, 3, 4, 5, 6, 7 }, // Adventures of Square

  { }, // Reserved

  { 1, 2, 3, 4, 5, 6, 7, 8 }, // Project MSX

  { 1, 2, 2, 2, 3, 3, 4, 5, 6, 7 }, // Accessories to Murder

  { // DoomRL Arsenal
    1, 1, 1, 1, 1, 1,
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
    3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
    4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
    5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
    6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
    7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
  },

  { 1, 1, 2, 3, 3, 4, 4, 5, 6, 7, 0 }, // High Noon Drifter

  { 1, 1, 2, 3, 3, 4, 5, 6, 7 }, // Freedoom

  { // X-Weapon
    1,
    2, 2, 2, 2,
    3, 3, 3, 3,
    4, 4, 4,
    5, 5, 5,
    6, 6, 6,
    7, 7, 7,
    8, 8, 8, 8,
    9, 9,
    0, 0,
  },

  { 1, 2, 3, 4, 5, 6 }, // Harmony

  { 1, 1, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 8 }, // Doom Delta

  { 1, 1, 2, 3, 3, 4, 5, 6, 7 }, // EVP

  { 1, 2, 2, 3, 4, 5, 5, 6, 7, 8, 9 }, // Factotum

  { // Flakes Doom
    1, 1, 1,
    2, 2,
    3, 3,
    4, 4, 4,
    5, 5, 5,
    6, 6,
    7, 7, 7, 7,
  },

  { 1, 2, 3,    4, 5, 5, 5, 6, 7, 7 }, // Guncaster - Heretic
  { 1, 2, 3, 3, 4, 5, 5, 5, 6, 7, 7 }, // Guncaster - Doom
  { 1, 2, 3, 3, 4, 5, 5, 5, 6, 7, 7 }, // Guncaster - Hexen
  { 1, 2, 3, 3, 4, 5, 5, 5, 6, 7, 7 }, // Guncaster - Strife

};

// List of weapon classes.
// Number of classes here must be equal to weapon count in weaponCounts array.
str names[SETS_NUMBER][MAX_WEAPONS_NUMBER] =
{
  { // Standard
    "Chainsaw", "Fist",
    "Pistol",
    "SuperShotgun", "Shotgun",
    "Chaingun",
    "RocketLauncher",
    "PlasmaRifle",
    "BFG9000"
  },

  { // PerK's Smoother Weapon Animations Enhanced + Smooth Doom
    "Z86Chainsaw", "PerkFist",
    "Rifle", "PerkPistol",
    "PerkSuperShotgun", "PerkShotgun",
    "Z86Chaingun",
    "PerkRocketLauncher",
    "BloxPlasmaRifle",
    "Z86BFG9000"
  },

  { // Eriguns 1
    "EriChainsaw", "EriFist",
    "EriPistol",
    "EriSuperShotgun",
    "EriShotgun",
    "EriMachinegun",
    "EriRocketLauncher",
    "EriPlasmaRifle",
    "EriBFG9000"
  },
  {
    "EriChainsaw", "EriFist",
    "AltPistol",
    "EriAutoShotgun", "AltSuperShotgun", "EriShotgun",
    "EriGatlingGun", "EriMachinegun",
    "EriMissileLauncher", "EriRocketLauncher",
    "EriPlasmaRifle",
    "EriBFG9000",
    "EriGrenadeLauncher"
  },

  { // abort_m
    "TileWeapon", "FingerPoke",
    "PeaShooter",
    "GunShotgun", "BoxOfPellets",
    "BigPee",
    "Lewd",
    "AstolfoWeapon",
    "ToolTim", "OuchWeapon",
    "AbortButton"
  },

  {
    "BD_Chainsaw", "BD_Fist",
    "BD_Pistol",
    "BD_SuperShotgun", "BD_Shotgun",
    "BD_Chaingun",
    "BD_RocketLauncher",
    "BD_PlasmaRifle",
    "BD_BFG9000"
  },

  {
    "FDPlutChainsaw", "FDPlutFist",
    "FDPlutPistol",
    "FDPlutSuperShotgun", "FDPlutShotgun",
    "FDPlutChaingun",
    "FDPlutRocketLauncher",
    "FDPlutPlasmaRifle",
    "FDPlutBFG9000"
  },
  {
    "FDTNTChainsaw", "FDTNTFist",
    "FDTNTPistol",
    "FDTNTSuperShotgun", "FDTNTShotgun",
    "FDTNTChaingun",
    "FDTNTRocketLauncher",
    "FDTNTPlasmaRifle",
    "FDTNTBFG9000"
  },
  {
    "FDDoom2Chainsaw", "FDDoom2Fist",
    "FDDoom2Pistol",
    "FDDoom2SuperShotgun", "FDDoom2Shotgun",
    "FDDoom2Chaingun",
    "FDDoom2RocketLauncher",
    "FDDoom2PlasmaRifle",
    "FDDoom2BFG9000"
  },
  {
    "FDAliensChainsaw", "FDAliensFist",
    "FDAliensPistol",
    "FDAliensSuperShotgun", "FDAliensShotgun",
    "FDAliensChaingun",
    "FDAliensRocketLauncher",
    "FDAliensPlasmaRifle",
    "FDAliensBFG9000"
  },
  {
    "FDJPCPFist",
    "FDJPCPPistol",
    "FDJPCPSuperShotgun", "FDJPCPShotgun",
    "FDJPCPChaingun",
    "FDJPCPRocketLauncher",
    "FDJPCPPlasmaRifle",
    "FDJPCPBFG9000"
  },
  {
    "FDBTSXChainsaw", "FDBTSXFist",
    "FDBTSXPistol",
    "FDBTSXSuperShotgun", "FDBTSXShotgun",
    "FDBTSXChaingun",
    "FDBTSXRocketLauncher",
    "FDBTSXPlasmaRifle",
    "FDBTSXBFG9000"
  },

  { // Faspons
    "Motorsaw", "Knuckles",
    "CombatRifle",
    "DoubleBarrel", "Riotgun",
    "Minigun",
    "RPG",
    "PulseRifle",
    "BFG"
  },

  { // Cyan-Doom
    "Magnetsaw", "Chainsaw", "Fist",
    "Rifle", "Pistol",
    "SuperShotgun", "Shotgun",
    "STMinigun", "Chaingun",
    "STGrenadeLauncher", "RocketLauncher",
    "STRailgun", "PlasmaRifle",
    "STBFG10K", "BFG9000",
    "SkullStaff"
  },

  { // Kriegsland
    "HDGrenades", "HDChainsaw", "HDKnife",
    "HDBlaster", "HDHandgun", "HDPistol",
    "HDSuperShotgun", "HDShotgun",
    "HDChaingun", "HDMachinegun",
    "HDPanzerfaust", "HDFlareGun", "HDRocketLauncher",
    "HDSonicGun", "HDLightningGun", "HDPlasmaRifle",
    "HDLaserGun", "HDLurdinha", "HDBFG9000",
    "HDCarbine", "HDGewehr", "HDRifle",
    "HDCrossAkimbo5", "HDCrossAkimbo4", "HDCrossAkimbo3", "HDCrossAkimbo2", "HDCrossAkimbo1",
  },

  { // Complex Doom
    "Chainsaw ", "Melee",
    "Handgun",
    "Quad Barrel Shotgun", "Double Barrel Shotgun", "Assault Shotgun", "Combat Shotgun",
    "Minigun ", "Assault Rifle",
    "Grenade Launcher", "Rocket Launcher",
    "Railgun ", "Demon Tech Rifle", "Plasma Rifle",
    "Demon Tech BFG10K", "BFG10K ", "BFG9500",
    "MP40",
  },

  { // Weapons of Saturn
    "Motorsaw", "Knuckles",
    "MP40", "1911", "Beretta",
    "Coachgun", "Riotgun",
    "Minigun", "MachineRifle",
    "SaturnV",
    "NovaRifle",
    "TITAN",
  },

  { // Hard-Doom
    "Chainsaw~", "Fist~",
    "Pistol~",
    "Quad-Shotgun", "SuperShotgun~", "Shotgun~",
    "Minigun~", "Chaingun~",
    "GrenadeLauncher~", "RocketLauncher~",
    "PlasmaRifle~", "Sonic Railgun",
    "BFG10K~", "BFG9000~",
  },

  { // REKKR
    "Chainsaw", "Fist",
    "Pistol",
    "Shotgun",
    "Chaingun",
    "RocketLauncher",
    "PlasmaRifle",
    "BFG9000"
  },

  { // Chex Quest
    "SuperBootspork", "Bootspoon",
    "MiniZorcher",
    "SuperLargeZorcher", "LargeZorcher",
    "RapidZorcher",
    "ZorchPropulsor",
    "PhasingZorcher",
    "LAZDevice",
  },

  { // Strife
    "PunchDagger",
    "StrifeCrossbow", "StrifeCrossbow2",
    "AssaultGun",
    "MiniMissileLauncher",
    "StrifeGrenadeLauncher", "StrifeGrenadeLauncher2",
    "FlameThrower",
    "Mauler", "Mauler2",
    "Sigil"
  },

  { // Argent
    "ArgChainsaw",
    "ArgFist",
    "ArgPistol",
    "ArgSuperShotgun",
    "ArgShotgun",
    "ArgChaingun",
    "ArgHeavyAR",
    "ArgRocketLauncher",
    "ArgGaussCannon",
    "ArgPlasmaRifle",
    "ArgBFG9000",
  },

  { // Doom 64
    "64Chainsaw", "64Fist",
    "64Uzi", "64Pistol",
    "64Devastator", "64SuperShotgun", "64Shotgun",
    "64Nailgun", "64Chaingun",
    "64Flamethrower", "64RocketLauncher",
    "64Railgun", "64PlasmaRifle",
    "Unmaker", "64BFG9000",
    "64Unmaker",
  },

  { // Responsive Weapons + Faster Weapon Switching
    "ChainsawFixed", "FistFixed",
    "PistolFixed",
    "SuperShotgunFixed", "ShotgunFixed",
    "ChaingunFixed",
    "RocketLauncherFixed",
    "PlasmaRifleFixed",
    "BFG9000Fixed"
  },

  { // Dead Marine
    "XtremeSaw", "Xtremefist",
    "XtremePistol",
    "XtremeSSG", "XtremeShotgun",
    "XtremeChaingun",
    "XtremeRLauncher",
    "XtremePlasma",
    "XtremeBFG"
  },

  { // Parkour
    "PkChainsaw", "PkFist",
    "PkPistolAkimbo", "PkPistol",
    "PkDoubleShotguns", "PkShotgun",
    "PkChaingun",
    "PkRocketLauncher",
    "PkPlasmaRifle",
    "PkBFG9000",
    "PkCyberLauncher",
    "PkSuperChain",
  },

  { // VSmooth
    "SmoothChainsaw" , "Fist",
    "Pistol"         ,
    "SuperShotgun"   , "Shotgun",
    "Chaingun"       ,
    "RocketLauncher" ,
    "PlasmaRifle"    ,
    "BFG9000"
  },

  { }, // Reserved

  { // Brutal Doom
    "Melee_Attacks", "Chain_saw", "BrutalAxe",
    "MP40", "BrutalSMG", "BrutalPistol",
    "SSG", "Shot_Gun", "AssaultShotgun",
    "HitlersBuzzsaw", "Minigun", "Rifle", "Machinegun",
    "Rocket_Launcher", "GrenadeLauncher",
    "Plasma_Gun", "Railgun",
    "BIG_FUCKING_GUN", "Unmaker", "BFG10k",
    "FlameCannon", "HellishMissileLauncher"
  },

  { }, // Reserved
  { }, // Reserved
  { }, // Reserved

  { // Trailblazer
    "Macheterang", "SpikebombWeapon",
    "Colts", "Sidekick",
    "Fleshrend", "ChromeJustice",
    "Leadspitter", "FMG",
    "Bitchmaker", "Patriarch",
    "Skullthrottle",
    "Nutcracker",
  },
  { // Trailblazer
    "Macheterang", "SpikebombWeapon",
    "Colts", "Sidekick",
    "Fleshrend", "ChromeJustice",
    "Leadspitter", "FMG",
    "Bitchmaker", "Patriarch",
    "Skullthrottle",
    "Nutcracker",
  },
  { // Trailblazer
    "Macheterang", "SpikebombWeapon",
    "Colts", "Sidekick",
    "Fleshrend", "ChromeJustice",
    "Leadspitter", "FMG",
    "Bitchmaker", "Patriarch",
    "Skullthrottle",
    "Nutcracker",
  },

  { // WW-Cola3
    "ColaHandgun",
    "PumpShotgun", "DualPumpShotgun",
    "CardThrower",
    "PlasmaAutorifle",
    "MissileLauncher",
    "Piledriver",
    "ToothpasteLaser",
  },
  { // WW-Cola3
    "ColaHandgun",
    "PumpShotgun", "DualPumpShotgun",
    "CardThrower",
    "PlasmaAutorifle",
    "MissileLauncher",
    "Piledriver",
    "ToothpasteLaser",
  },

  { // Netronian Chaos
    "LB1000PileBanger", "AnaikaDagger", "M101Blade",
    "EG10HeavyPistol", "V57BurstPistol", "V96ServicePistol",
    "FASR33AssaultSupporter", "VS4Sweeper", "VS2Riotgun",
    "PAG20PDW", "V80BSMG", "V88Carbine",
    "VARACarbine", "AG100Machinegun", "V74ARifle",
    "M12FMGR", "V32AARifle", "V50MLauncher",
    "M189Auto", "V99AThrower", "VE1Coilgun",
    "HeavyBarrel", "VM201TD", "Ver110VC"
  },

  { // Adventures of Square
    "PaintGuns", "PaintGun",
    "Oozis", "Oozi",
    "Quadcannon", "Shotbow",
    "PaintCannon",
    "HellShellLauncher",
    "Sceptre",
    "Defibrillator"
  },

  { }, // Reserved

  { // Project MSX
    "RegularFists",
    "golampistol",
    "hydrashotgun",
    "barracudarifle",
    "raptorshotgun",
    "tauruscannon",
    "chimerarifle",
    "orionSniper"
  },

  { // Accessories to Murder
    "Sledge",
    "Revolver", "DNDualPistol", "DNPistol",
    "TrenchShotgun", "DoubleShotgun",
    "DNRifle",
    "DNRocketLauncher",
    "DNChaingun",
    "DNBFG"
  },

  { // DoomRL Arsenal
    "RLEnergysaw",
    "RLPiercingChainsaw",
    "RLChainsaw",
    "RLRipper",
    "RLDoubleChainsaw",
    "RLFistRedux",
    "RLNanomanufactureAmmoDesertEagle",
    "RLNanoManufactureAmmoMarksmanPistol",
    "RLNanomanufactureAmmoCombatPistol",
    "RLNanomanufactureAmmoBlaster",
    "RLNanoManufactureAmmoPistol",
    "RLHeavyPulseBlaster",
    "RLOverchargedBlaster",
    "RLPlasmaDesertEagle",
    "RLPlasmaCombatPistol",
    "RLPlasmaPistol",
    "RLStormBlaster",
    "RLStormDesertEagle",
    "RLStormMarksmanPistol",
    "RLStormCombatPistol",
    "RLStormPistol",
    "RLHighPowerPP7",
    "RLHighPowerHuntingRevolver",
    "RLHighPowerDesertEagle",
    "RLHighPowerMarksmanPistol",
    "RLHighPowerCombatPistol",
    "RLHighPowerBlaster",
    "RLHighPowerPistol",
    "RLSpeedloaderPistol",
    "RLSilencedPistol",
    "RLNeuralStunner",
    "RLDeathsGaze",
    "RLTrigun",
    "RLHellsingARMSCasull",
    "RLAntiFreakJackal",
    "RLGrammatonClericBeretta",
    "RLUnknownHerald",
    "RLMysteriousMagnum",
    "RLPP7",
    "RLHuntingRevolver",
    "RLDesertEagle",
    "RLMarksmanPistol",
    "RLCombatPistol",
    "RLBlaster",
    "RLPistol",
    "RLConquerorShotgun",
    "RLMegatonShotgun",
    "RLNanoShrapnelAssaultShotgun",
    "RLNanoShrapnelSuperShotgun",
    "RLNanoShrapnelDoubleShotgun",
    "RLNanoShrapnelCombatShotgun",
    "RLNanoShrapnelShotgun",
    "RLAutoDoubleShotgun",
    "RLAutoShotgun",
    "RLFocusedDoubleShotgun",
    "RLPlasmaticShrapnelHuntingShotgun",
    "RLPlasmaticShrapnelAssaultShotgun",
    "RLPlasmaticShrapnelSuperShotgun",
    "RLPlasmaticShrapnelDoubleShotgun",
    "RLPlasmaticShrapnelCombatShotgun",
    "RLPlasmaticShrapnelShotgun",
    "RLHeavyHuntingShotgun",
    "RLHeavyAssaultShotgun",
    "RLHeavySuperShotgun",
    "RLHeavyDoubleShotgun",
    "RLHeavyCombatShotgun",
    "RLHeavyShotgun",
    "RLTacticalShotgun",
    "RLElephantGun",
    "RLShredderShotgun",
    "RLShredderPistol",
    "RLJudgeOfTheDead",
    "RLMarathonShotguns",
    "RLSteelBeast",
    "RLQuadShotgun",
    "RLFragShotgun",
    "RLJackhammer",
    "RLHuntingShotgun",
    "RLSuperShotgun",
    "RLAssaultShotgun",
    "RLDoubleShotgun",
    "RLCombatShotgun",
    "RLShotgun",
    "RLNanoManufactureAmmoUzi",
    "RLNanoManufactureAmmoMinigun",
    "RLNanomanufactureAmmoBattleRifle",
    "RLNanoManufactureAmmoChaingun",
    "RLAntiMaterielRifle",
    "RLSuperMachinegun",
    "RLBurstCannonUzi",
    "RLBurstCannonMinigun",
    "RLBurstCannonBattleRifle",
    "RLBurstCannonChaingun",
    "RLAssaultRifleUzi",
    "RLAssaultRifleMinigun",
    "RLAssaultRifleBattleRifle",
    "RLAssaultRifleChaingun",
    "RLBulletstormRifle",
    "RLBulletstormChaingun",
    "RLStormUzi",
    "RLHighPowerRCP90",
    "RLHighPowerThompson",
    "RLHighPowerVanguardRifle",
    "RLHighPowerMarksmanRifle",
    "RLHighPowerUzi",
    "RLHighPowerMinigun",
    "RLHighPowerBattleRifle",
    "RLHighPowerChaingun",
    "RLSniperRifle",
    "RLGatlingGun",
    "RLStealthRifle",
    "RLSoulstormRifle",
    "RLNanomachicArmamentGenerator",
    "RLWidowmakerSMG",
    "RLMarathonAssaultRifle",
    "RLRCP90",
    "RLThompson",
    "RLVanguardRifle",
    "RLMarksmanRifle",
    "RLUzi",
    "RLMinigun",
    "RLBattleRifle",
    "RLChaingun",
    "RLDemolitionAmmoUzi",
    "RLDemolitionAmmoMinigun",
    "RLDemolitionAmmoDesertEagle",
    "RLDemolitionAmmoMarksmanPistol",
    "RLDemolitionAmmoCombatPistol",
    "RLDemolitionAmmoChaingun",
    "RLDemolitionAmmoBattleRifle",
    "RLDemolitionAmmoPistol",
    "RLNanoManufactureAmmoNapalmLauncher",
    "RLNanoManufactureAmmoMissileLauncher",
    "RLNanomanufactureAmmoTristarBlaster",
    "RLNanomanufactureAmmoRocketLauncher",
    "RLIncinerationDeviceLauncher",
    "RLLaserPulseLauncher",
    "RLInfusionLauncher",
    "RLClusterBombLauncher",
    "RLAutocannon",
    "RLMotherInLaw",
    "RLGrenadeLauncher",
    "RLMiniMissilePistol",
    "RLTacticalRocketLauncher",
    "RLHighPowerTristarBlaster",
    "RLShrapnelCannon",
    "RLMicroLauncher",
    "RLHurricaneCannon",
    "RLMIRVLauncher",
    "RLRevenantsLauncher",
    "RLTantrumCannon",
    "RLNapalmLauncher",
    "RLMissileLauncher",
    "RLTristarBlaster",
    "RLRocketLauncher",
    "RLNanoManufactureAmmoLaserRifle",
    "RLNanomanufactureAmmoPlasmaRifle",
    "RLLaserMinigun",
    "RLPlasmaCannon",
    "RLGaussRifle",
    "RLVoltgun",
    "RLPlasmaRefractor",
    "RLNanoShrapnelPlasmaShotgun",
    "RLBurstCannonNuclearPlasmaRifle",
    "RLBurstCannonLaserRifle",
    "RLBurstCannonPlasmaRifle",
    "RLAssaultRifleNuclearPlasmaRifle",
    "RLAssaultRifleLaserRifle",
    "RLAssaultRiflePlasmaRifle",
    "RLNuclearPlasmaShotgun",
    "RLPlasmaShotgunMkII",
    "RLLaserShotgun",
    "RLNuclearPlasmaRifleMkII",
    "RLPlasmaRifleMkII",
    "RLHyperblaster",
    "RLSuperchargedNuclearPlasmaPistol",
    "RLPlasmaUzi",
    "RLPlasmaMarksmanPistol",
    "RLStormNuclearPlasmaPistol",
    "RLPlasmaticShrapnelPlasmaShotgun",
    "RLHighPowerNuclearPlasmaRifle",
    "RLHighPowerNuclearPlasmaPistol",
    "RLHighPowerLaserRifle",
    "RLHighPowerPlasmaRifle",
    "RLHeavyPlasmaShotgun",
    "RLNuclearPlasmaRevolver",
    "RLFlamethrower",
    "RLDuke2Rifle",
    "RLUnmaker",
    "RLHellsReign",
    "RLNuclearOnslaught",
    "RLChameleonRifle",
    "RLSussGun",
    "RLPlasmaRedirectionCannon",
    "RLLightweaver",
    "RLRailgun",
    "RLCombatTranslocator",
    "RLNuclearPlasmaRifle",
    "RLNuclearPlasmaPistol",
    "RLLaserRifle",
    "RLPlasmaShotgun",
    "RLPlasmaRifle",
    "RLZeusCannon",
    "RLNuclearBiggestFuckingGun",
    "RLBiggestFuckingGun",
    "RLNuclearVBFG9000",
    "RLVBFG9000",
    "RLHighPowerNuclearBFG9000",
    "RLHighPowerBFG9000",
    "RLBFGInfinity",
    "RLRealityDistortionArray",
    "RLBaronBlaster",
    "RLParticleBeamCannon",
    "RLNullPointer",
    "RLBFG10K",
    "RLNuclearBFG9000",
    "RLBFG9000"
  },

  { // High Noon Drifter
    "Boomerang", "Bow",
    "Revolver",
    "Coachgun", "Winchester",
    "SMGs", "SMG",
    "Grenades",
    "DarkStaff",
    "Artifact",
    "DoubleWhips",
  },

  { // Freedoom
    "Chainsaw", "Fist",
    "Pistol",
    "SuperShotgun", "Shotgun",
    "Chaingun",
    "RocketLauncher",
    "PlasmaRifle",
    "BFG9000"
  },

  { // X-Weapon
    "FistX",

    "XPistolXX",
    "SPistolX",
    "BFDPistolX",
    "PistolX",

    "HavokCannon",
    "XShotgunX",
    "SShotgunX",
    "ShotgunX",

    "XAssaultRifleX",
    "SAssaultRifleX",
    "AssaultRifleX",

    "XSuperShotgunX",
    "SSuperShotgunX",
    "SuperShotgunX",

    "XPhaseLauncherX",
    "SPhaseLauncherX",
    "PhaseLauncherX",

    "XPlasmaRifleX",
    "SDemontechRifleX",
    "DemontechRifleX",

    "XBFSGX",
    "XBFGGX",
    "SBFGX",
    "BFGX",

    "GrenadeCannonX",
    "ChaingunX",

    "DPistolX",
    "XPistolX",
  },

  { // Harmony
    "Fist",
    "Pistol",
    "Shotgun",
    "Chaingun",
    "RocketLauncher",
    "PlasmaRifle",
  },

  { // Doom Delta
    "ChainsawBeta", "Bayonette",
    "Rifle",
    "SuperShotgunBeta", "ShotgunBeta",
    "ChaingunBeta", "MachineGun",
    "RocketLauncherBeta", "GrenadeLauncherBeta",
    "DarkClaw", "PlasmaRifleBeta",
    "BFGBeta",
    "UnmakerDelta",
  },

  { // EVP
    "PerkChainsaw", "PerkFist",
    "PerkPistol",
    "PerkSuperShotgun", "PerkShotgun",
    "PerkChaingun",
    "PerkRocketLauncher",
    "PerkPlasmaRifle",
    "PerkBFG9000",
  },

  { // Factotum
    "FKMachete",
    "FKPistol", "FKPistolUP",
    "FKShotgun",
    "FKMachinegun",
    "FKLauncher", "FKLauncherUP",
    "FKPlasmaRifle",
    "FKCarbine",
    "FKHoser",
    "FKGrenades",
  },

  { // Flakes Doom
    "FKChainsaw", "FKMCGT", "FKFist",
    "FKMachinegun", "FKPistol",
    "FKSupershotgun", "FKShotgun",
    "FKROTTCG", "FKChaingun", "FKHAR",
    "FKROTTRL", "FKRocketLauncher", "FKGrenades",
    "FKROTTPL", "FKPlasmaRifle",
    "FKROTTB9", "FKHexenUnmaker", "FKBFG9000", "FKUnmaker",
  },

  { // Guncaster - Heretic
    "Dergfist"       ,
    "Longhorn"       ,
    "Strucker"       ,
    "Pulverizer"     ,
    "MourningGlory"  , "Matriarch"  , "DynamiteWeapon",
    "Augur"          ,
    "GoldenEmperor"  , "OldDreadful"
  },

  { // Guncaster - Doom
    "Dergfist"       ,
    "Longhorn"       ,
    "Ironblast"      , "Strucker"   ,
    "Pulverizer"     ,
    "MourningGlory"  , "Matriarch"  , "DynamiteWeapon",
    "Augur"          ,
    "GoldenEmperor"  , "OldDreadful"
  },

  { // Guncaster - Hexen
    "Dergfist"       ,
    "Longhorn2"      ,
    "Ironblast2"     , "Strucker2"  ,
    "Pulverizer2"    ,
    "MourningGlory2" , "Matriarch2" , "DynamiteWeapon",
    "Augur2"         ,
    "GoldenEmperor"  , "OldDreadful2"
  },

  { // Guncaster - Strife
    "Dergfist"       ,
    "Longhorn"       ,
    "Ironblast"      , "Strucker"   ,
    "Pulverizer"     ,
    "MourningGlory"  , "Matriarch"  , "DynamiteWeapon",
    "Augur"          ,
    "GoldenEmperor"  , "OldDreadful"
  },

}; // end of actor/class names /////////////////////////////////////////////////

// List of weapon names (tags).
// Number of names here must be equal to weapon count in weaponCounts array.
str tags[SETS_NUMBER][MAX_WEAPONS_NUMBER] =
{
  { // Doom
    "Chainsaw", "Brass Knuckles",
    "Pistol",
    "Super Shotgun", "Shotgun",
    "Chaingun",
    "Rocket Launcher",
    "Plasma Rifle",
    "BFG 9000"
  },

  { // PerK's Smoother Weapon Animations Enhanced + Smooth Doom
    "Chainsaw", "Fist",
    "Rifle", "Pistol",
    "Super Shotgun", "Shotgun",
    "Chaingun",
    "Rocket Launcher",
    "Plasma Rifle",
    "BFG9000"
  },

  { // Eriguns
    "Chainsaw", "Fist",
    "Pistol",
    "Super Shotgun", "Shotgun",
    "Chaingun",
    "Rocket Launcher",
    "Plasma Rifle",
    "BFG9000"
  },
  {
    "Chainsaw", "Fist",
    "Pistol",
    "Auto Shotgun", "Super Shotgun", "Shotgun",
    "Gatling Gun", "Machinegun",
    "Missile Launcher", "Rocket Launcher",
    "Plasma Rifle",
    "BFG9000",
    "Grenade Launcher"
  },

  { // abort_m
    "Floor Tile", "Finger poke",
    "Pea shooter",
    "Gunshotgun", "Pellet Box",
    "Big P",
    "Assblaster",
    "Astolfo plush",
    "Tim Allen", "Ouch Face",
    "Abort button"
  },

  { // Beautiful Doom
    "Chainsaw", "Fist",
    "Pistol",
    "Super Shotgun", "Shotgun",
    "Chaingun",
    "Rocket Launcher",
    "Plasma Rifle",
    "BFG9000"
  },

  { // Final Doomer
    "Power Saw", "Melee",
    "Ol' Faithful",
    "Super Shotgun", "Scoped Shotgun",
    "Machine Gun",
    "Grenade Launcher",
    "Heavy Machine Gun",
    "Quantum Accelerator"
  },
  {
    "Halderman Device", "Melee",
    "Prototype Pistol",
    "Burst Shotgun", "Tactical Shotgun",
    "Dual Uzis",
    "Missile Launcher",
    "Maser",
    "Incursion Annihilator"
  },
  {
    "Chainsaw", "Melee",
    "Pistol",
    "Super Shotgun", "Shotgun",
    "Chaingun",
    "Rocket Launcher",
    "Plasma Rifle",
    "BFG 9000"
  },
  {
    "Stasis Bow", "Trench Knife",
    "Ancient Pistol",
    "Hybrid SSG", "Ancient Shotgun",
    "Ancient AK",
    "Photon Scepter",
    "Alien Elite Weapon",
    "Illuminator"
  },
  {
    "Katana",
    "Silenced Pistol",
    "Neutron Cascader", "Neutron Pulser",
    "Burst Needler",
    "Prism Cannon",
    "Ofuda Caster",
    "Onmyou Devastator"
  },
  {
    "NanoCore", "Power Fist",
    "Charge Pistol",
    "Machreaper", "Arc Blaster",
    "Pulse Rifle",
    "Pulse Cannon",
    "Plasma Vulcan",
    "X-Spark Cannon"
  },

  { // Faspons
    "Chainsaw", "Knuckles",
    "Combat Rifle",
    "Double Barrel Shotgun", "Riotgun",
    "Minigun",
    "RPG",
    "Pulse Rifle",
    "BFG9000"
  },

  { // Cyan-Doom
    "Super Chainsaw", "Chainsaw", "Brass Knuckles",
    "Rifle", "Pistol",
    "Super Shotgun", "Shotgun",
    "Minigun", "Chaingun",
    "Grenade Launcher", "Rocket Launcher",
    "Railgun", "Plasma Rifle",
    "BFG10K", "BFG 9000",
    "Skull Staff",
  },

  { // Kriegsland
    "Stielhandgranate-68", "Elektroshocker", "Kampfmesser 84",
    "DL-44 FuturPistole-Blaster", "Mauser M972-S2", "Luger P-58",
    "Jadtfaust Wunderfilnte-8", "Luftwaffe DP-65",
    "MP-86s", "StG-60",
    "Panzerkreuz Mk. III", "Kampfpistole", "Lawine-6",
    "Schallkraftwerk", "Blitzgewehr", "Flammenfaust",
    "Ekelhaftwaffe", "MG-92", "VFR-245 Puls-Kanone",
    "Bombenschuss", "Gewehr-1953", "KAR 82a-2K",
    "Cross Thermals", "Cross Launchers", "Cross Machineguns", "Cross Shotguns", "Cross Pistols",
  },

  { // Complex Doom
    "Chainsaw", "Melee",
    "Handgun",
    "Quad Barrel Shotgun", "Double Barrel Shotgun", "Assault Shotgun", "Combat Shotgun",
    "Minigun", "Assault Rifle",
    "Grenade Launcher", "Rocket Launcher",
    "Railgun", "Demon Tech Rifle", "Plasma Rifle",
    "Demon Tech BFG10K", "BFG10K", "BFG9500",
    "MP40",
  },

  { // Weapons of Saturn
    "Chain Saw", "Knuckles",
    "MP40", "1911", "Beretta",
    "Coach Gun", "Riot Gun",
    "Rotary Cannon", "Machine Rifle",
    "Saturn V",
    "Nova Rifle",
    "Titan",
  },

  { // Hard-Doom
    "Chainsaw", "Fist",
    "Pistol",
    "Quad-Shotgun", "Super Shotgun", "Shotgun",
    "Minigun", "Chaingun",
    "Grenade Launcher", "Rocket Launcher",
    "Plasma Rifle", "Sonic Railgun",
    "BFG10K", "BFG9000",
  },

  { // REKKR
    "Axe", "Fists",
    "Soul Bow",
    "Steelshot Launcher",
    "Soul Launcher",
    "Runic Staff",
    "Holy Relic",
    "Blessing of the Gods"
  },

  { // Chex Quest
    "Super Bootspork", "Spoon",
    "Mini Zorcher",
    "Super-Large Zorcher", "Large Zorcher",
    "Rapid Zorcher",
    "Zorch Propulsor",
    "Phasing Zorcher",
    "LAZ Device",
  },

  { // Strife
    "Dagger",
    "Crossbow: Electric Bolts",
    "Crossbow: Poison Bolts",
    "Assault Gun",
    "Mini Missile Launcher",
    "Grenade Launcher: HE",
    "Grenade Launcher: Phosphorus",
    "Flame Thrower",
    "Mauler: Scatter",
    "Mauler: Torpedo",
    "SIGIL"
  },

  { // Argent
    "Chainsaw",
    "Fists",
    "Pistol",
    "Super Shotgun",
    "Combat Shotgun",
    "Chaingun",
    "Heavy Assault Rifle",
    "Rocket Launcher",
    "Gauss Cannon",
    "Plasma Rifle",
    "BFG 9000",
  },

  { // Doom 64
    "Chainsaw", "Fist",
    "Uzi", "Pistol",
    "Devastator", "Super Shotgun", "Shotgun",
    "Nailgun", "Chaingun",
    "Flamethrower", "Rocket Launcher",
    "Railgun", "Plasma Rifle",
    "Unmaker", "BFG 9000",
    "Unmaker",
  },

  { // Responsive Weapons + Faster Weapon Switching
    "Chainsaw", "Brass Knuckles",
    "Pistol",
    "Super Shotgun", "Shotgun",
    "Chaingun",
    "Rocket Launcher",
    "Plasma Rifle",
    "BFG 9000"
  },

  { // Dead Marine
    "Chainsaw", "Brass Knuckles",
    "Pistol",
    "Super Shotgun", "Shotgun",
    "Chaingun",
    "Rocket Launcher",
    "Plasma Rifle",
    "BFG 9000"
  },

  { // Parkour
    "Chainsaw", "Fists",
    "Akimbo Pistols", "Pistol",
    "Dual Sawnoffs", "Shotgun",
    "Chaingun",
    "Rocket Launcher",
    "Plasma Rifle",
    "BFG 9000",
    "Cyber Launcher",
    "Super Chaingun",
  },

  { // VSmooth
    "Chainsaw"        , "Brass Knuckles",
    "Pistol"          ,
    "Super Shotgun"   , "Shotgun",
    "Chaingun"        ,
    "Rocket Launcher" ,
    "Plasma Rifle"    ,
    "BFG 9000"
  },

  {}, // Reserved

  { // Brutal Doom
    "Melee", "Chainsaw", "Axe",
    "MP40", "SMG", "Pistol",
    "SSG", "Shotgun", "AA-12 Assault Shotgun",
    "Hitler's Buzzsaw", "Minigun", "Assault Rifle", "Machine Gun",
    "Rocket Launcher", "Grenade Launcher",
    "Plasma Gun", "Railgun",
    "BFG-9000", "Unmaker", "BFG10K",
    "Flame Cannon", "Hellish Missile Launcher"
  },

  { }, // Reserved
  { }, // Reserved
  { }, // Reserved

  { // Trailblazer
    "Macheterang", "Spikebombs",
    "Cradle & Grave", "Sidekick",
    "Fleshrend", "Chrome Justice",
    "Leadspitter", "F.M.G.",
    "Bitchmaker", "Patriarch",
    "Skullthrottle",
    "Nutcracker",
  },
  { // Trailblazer
    "Macheterang", "Spikebombs",
    "Cradle & Grave", "Sidekick",
    "Fleshrend", "Chrome Justice",
    "Leadspitter", "F.M.G.",
    "Bitchmaker", "Patriarch",
    "Skullthrottle",
    "Nutcracker",
  },
  { // Trailblazer
    "Macheterang", "Spikebombs",
    "Cradle & Grave", "Sidekick",
    "Fleshrend", "Chrome Justice",
    "Leadspitter", "F.M.G.",
    "Bitchmaker", "Patriarch",
    "Skullthrottle",
    "Nutcracker",
  },

  { // WW-Cola3
    "Marston R-1 Techvolver",
    "KS-23 Shotgun", "Dual KS-23 Shotguns",
    "Kare Brand Cards",
    "Plasma Autorifle",
    "Sidewinder Missile Launcher",
    "Piledriver",
    "Toothpaste Laser",
  },
  { // WW-Cola3
    "Marston R-1 Techvolver",
    "KS-23 Shotgun", "Dual KS-23 Shotguns",
    "Kare Brand Cards",
    "Plasma Autorifle",
    "Sidewinder Missile Launcher",
    "Piledriver",
    "Toothpaste Laser",
  },

  { // Netronian Chaos
    "Pile Banger Glove", "Anaika Hunting Daggers", "Digitalblade",
    "Heavy Caliber Pistol", "Burst Pistol", "Service Pistol",
    "Assault Supporter", "Hand Sweeper", "Riotgun",
    "Personal Defence Arm", "Burst SMG", "Machine Carbine",
    "Semi Auto Rifle", "Squad Support Gun", "Combat Rifle",
    "Cyro Grenade Bouncer", "Anti Armor Rifle", "Missile Launcher",
    "Full Auto LAWF", "Personal Annihilator", "Semi Coil Carbine",
    "Fierce Caliber", "Tri Desolator", "Heavy Vulcan"
  },

  { // Adventures of Square
    "Dual Paint Guns", "Paint Gun",
    "Dual Oozis", "Oozi",
    "Quad Cannon", "Shotbow",
    "Paintgun Cannon",
    "Hellshell Launcher",
    "Cresceptre",
    "Defibrillator"
  },

  { }, // Reserved

  { // Project MSX
    "Fists",
    "Golam Pistol",
    "Hydra Shotgun",
    "Barracuda Rifle",
    "Raptor NailShotgun",
    "Taurus AutoCannon",
    "Chimaera Pulse Rifle",
    "Orion Gauss Cannon"
  },

  { // Accessories to Murder
    "Sledge Hammer",
    "Revolver", "Pistols (Akimbo)", "Pistol",
    "Shotgun", "Sawed-Off",
    "Assault Rifle",
    "Rocket Launcher",
    "Chaingun",
    "Bergmann Field Generator"
  },

  { // DoomRL Arsenal
    "Energysaw",
    "Nanoedge Chainsaw",
    "Chainsaw",
    "Ripper",
    "Double Chainsaw",
    "Unarmed",
    "Nanomachic Handcannon",
    "Nanomachic Marksman Pistol",
    "Nanomachic Combat Pistol",
    "Nanomachic Blaster",
    "Nanomachic Pistol",
    "Heavy Pulse Blaster",
    "Overcharged Blaster",
    "Plasma Handcannon",
    "Plasma Combat Pistol",
    "Plasma Pistol",
    "Storm Blaster",
    "Storm Handcannon",
    "Storm Marksman Pistol",
    "Storm Combat Pistol",
    "Storm Pistol",
    "High Power PP7",
    "High Power Hunting Revolver",
    "High Power Handcannon",
    "High Power Marksman Pistol",
    "High Power Combat Pistol",
    "High Power Blaster",
    "High Power Pistol",
    "Revolver",
    "Silenced Pistol",
    "Neural Stunner",
    "Death's Gaze",
    "Trigun",
    "Hellsing ARMS Casull",
    "Anti-Freak Jackal",
    "Grammaton Cleric Beretta",
    "Unknown Herald",
    "Mysterious Magnum",
    "PP7",
    "Hunting Revolver",
    "Handcannon",
    "Marksman Pistol",
    "Combat Pistol",
    "Blaster",
    "Pistol",
    "Conqueror Shotgun",
    "Megaton Shotgun",
    "Nano Assault Shotgun",
    "Nano Super Shotgun",
    "Nano Double Shotgun",
    "Nano Combat Shotgun",
    "Nano Shotgun",
    "Auto Double Shotgun",
    "Auto Shotgun",
    "Focused Double Shotgun",
    "Plasmatic Hunting Shotgun",
    "Plasmatic Assault Shotgun",
    "Plasmatic Super Shotgun",
    "Plasmatic Double Shotgun",
    "Plasmatic Combat Shotgun",
    "Plasmatic Shotgun",
    "Heavy Hunting Shotgun",
    "Heavy Assault Shotgun",
    "Heavy Super Shotgun",
    "Heavy Double Shotgun",
    "Heavy Combat Shotgun",
    "Heavy Shotgun",
    "Tactical Shotgun",
    "Elephant Gun",
    "Shredder Shotgun",
    "Shredder Pistol",
    "Judge of the Dead",
    "WSTE-M5 Shotguns",
    "Steel Beast",
    "Quad Shotgun",
    "Frag Shotgun",
    "Jackhammer",
    "Hunting Shotgun",
    "Super Shotgun",
    "Assault Shotgun",
    "Double Shotgun",
    "Combat Shotgun",
    "Shotgun",
    "Nanomachic Uzi",
    "Nanomachic Minigun",
    "Nanomachic Battle Rifle",
    "Nanomachic Chaingun",
    "Anti-materiel Rifle",
    "Super Machinegun",
    "Burst Uzi",
    "Burst Minigun",
    "Burst-Fire Rifle",
    "Burst Chaingun",
    "Assault Uzi",
    "Assault Minigun",
    "Scoped Rifle",
    "Assault Chaingun",
    "Bulletstorm Rifle",
    "Bulletstorm Chaingun",
    "Dual Uzis",
    "RC-P120",
    "High Power Tommygun",
    "High Power Vanguard Rifle",
    "High Power Marksman Rifle",
    "High Power Uzi",
    "High Power Minigun",
    "High Power Battle Rifle",
    "High Power Chaingun",
    "Sniper Rifle",
    "Gatling Gun",
    "Stealth Rifle",
    "Soulstorm Rifle",
    "Nanomachic Armament Generator",
    "Widowmaker SMG",
    "MA-75B Assault Rifle",
    "RC-P90",
    "Tommygun",
    "Vanguard Rifle",
    "Marksman Rifle",
    "Uzi",
    "Minigun",
    "Battle Rifle",
    "Chaingun",
    "Demolition Ammo Uzi",
    "Demolition Ammo Minigun",
    "Demolition Ammo Handcannon",
    "Demolition Ammo Marksman Pistol",
    "Demolition Ammo Combat Pistol",
    "Demolition Ammo Chaingun",
    "Demolition Ammo Battle Rifle",
    "Demolition Ammo Pistol",
    "Nanomachic Napalm Launcher",
    "Nanomachic Missile Launcher",
    "Nanomachic Tristar Blaster",
    "Nanomachic Rocket Launcher",
    "Incineration Device Launcher",
    "Defence Drone Launcher",
    "Plascharge Launcher",
    "Cluster Bomb Launcher",
    "Autocannon",
    "Mother-In-Law",
    "Grenade Launcher",
    "Mini-missile Pistol",
    "Tactical Rocket Launcher",
    "High Power Tristar Blaster",
    "Shrapnel Cannon",
    "Micro Launcher",
    "Hurricane Cannon",
    "MIRV Launcher",
    "Revenant's Launcher",
    "Quantum Tantrum Cannon",
    "Napalm Launcher",
    "Missile Launcher",
    "Tristar Blaster",
    "Rocket Launcher",
    "Nanomachic Laser Rifle",
    "Nanomachic Plasma Rifle",
    "Laser Minigun",
    "Plasma Cannon",
    "Gauss Rifle",
    "Voltgun",
    "Plasma Refractor",
    "Nano Plasma Shotgun",
    "Burst Nuclear Plasma Rifle",
    "Burst Laser Rifle",
    "Burst Plasma Rifle",
    "Assault Nuclear Plasma Rifle",
    "Assault Laser Rifle",
    "Assault Plasma Rifle",
    "Nuclear Plasma Shotgun",
    "Plasma Shotgun Mk. II",
    "Laser Shotgun",
    "Nuclear Plasma Rifle Mk. II",
    "Plasma Rifle Mk. II",
    "Hyperblaster",
    "Supercharged Nuclear Plasma Pistol",
    "Plasma Uzi",
    "Plasma Marksman Pistol",
    "Storm Nuclear Plasma Pistol",
    "Overcharged Plasma Shotgun",
    "High Power Nuclear Plasma Rifle",
    "High Power Nuclear Plasma Pistol",
    "High Power Laser Rifle",
    "High Power Plasma Rifle",
    "Heavy Plasma Shotgun",
    "Nuclear Plasma Revolver",
    "Flamethrower",
    "Rigelatin Assault Weapon",
    "Unmaker",
    "Hell's Reign",
    "Nuclear Onslaught",
    "Chameleon Rifle",
    "Suss Gun",
    "Plasma Redirection Cannon",
    "Lightweaver",
    "Railgun",
    "Combat Translocator",
    "Nuclear Plasma Rifle",
    "Nuclear Plasma Pistol",
    "Laser Rifle",
    "Plasma Shotgun",
    "Plasma Rifle",
    "Zeus Cannon",
    "Biggest Fucking Nuclear Gun",
    "Biggest Fucking Gun",
    "Nuclear VBFG9000",
    "VBFG9000",
    "High Power Nuclear BFG9000",
    "High Power BFG9000",
    "BFG Infinity",
    "Reality Distortion Array",
    "Baron Blaster",
    "Particle Beam Cannon",
    "Charch's Null Pointer",
    "BFG10K",
    "Nuclear BFG9000",
    "BFG9000"
  },

  { // High Noon Drifter
    "Nimurdal", "Heki",
    "Thunderhawk",
    "Montaraz 1899", "Cintia 1901",
    "M-12 Grasa x2", "M-12 Grasa",
    "V45 Grenades",
    "Anthrakia",
    "Basilissa",
    "Whips",
  },

  { // Freedoom
    "Angle Grinder", "Fists",
    "Handgun",
    "Double-barrelled Shotgun", "Pump-action Shotgun",
    "Minigun",
    "Missile Launcher",
    "Polaric Energy Cannon",
    "SKAG 1337",
  },

  { // X-Weapon
    "Fist", // 0

    "Magnum Handcannon", // 1
    "Nighthawk", // 2 upgraded
    "Bluetail Pistol", // 3
    "Nighthawk", // 4

    "Havok Cannon", // 5
    "Tactical Shotgun", // 6
    "Shotgun", // 7 upgrade
    "Shotgun", // 8

    "Legion Light Rifle", // 9
    "Upgraded Assault Rifle", // 10 upgrade?
    "Assault Rifle", // 11

    "Automatic Shotgun", // 12
    "Quadruple Barreled Shotgun", // 13 upgrade
    "Double Barreled Shotgun", // 14

    "Cluster Torpedo Launcher", // 15
    "Phasic Cluster Launcher", // 16 upgrade
    "Phasic Cluster Launcher", // 17

    "Dual Neutron Disruptor", // 18
    "Demontech Rifle", // 19 upgrade
    "Demontech Rifle", // 20

    "BFSG", // 21
    "BFGG", // 22
    "BFG", // 23 upgrade
    "BFG", // 24

    "Grenade Cannon", // 25
    "Chaingun", // 26

    "Fatman Pistol", // 27
    "Bluetail pistol", // 28
  },

  { // Harmony
    "Grenade",
    "Neutron Gun",
    "Compensator",
    "Minigun",
    "Grenade launcher",
    "Entrophy thrower",
  },

  { // Doom Delta
    "Chainsaw", "Bayonet",
    "Rifle",
    "Super Shotgun", "Shotgun",
    "Chaingun", "Machine Gun",
    "Rocket Launcher", "Grenade Launcher",
    "Dark Claw", "Plasma Rifle",
    "BFG 2704",
    "Unmaker",
  },

  { // EVP
    "Chainsaw", "Brass Knuckles",
    "Pistol",
    "Super Shotgun", "Shotgun",
    "Chaingun",
    "Rocket Launcher",
    "Plasma Rifle",
    "BFG 9000"
  },

  { // Factotum
    "Machete",
    "Beretta 92FS", "Upgraded Beretta 92",
    "Franchi SPAS-12",
    "Calico M950",
    "Springfield M79", "Upgraded M79",
    "Plasma Cannon",
    "Colt M4A1",
    "FNH M249",
    "Grenades",
  },

  { // Flakes Doom
    "UAC Painsaw", "Mace and Gauntlet", "Melee Attacks",
    "Machinegun", "EnerPlas UAC Sidearm",
    "Super Shotgun", "Shotgun",
    "Chaingun", "Chaingun", "Heavy Assault Rifle",
    "Rocket Launcher", "Rocket Launcher", "Grenades",
    "Plasma Rifle", "Plasma Rifle",
    "BFG-9000", "Unmaker", "BFG-9000", "Unmaker",
  },

  { // Guncaster - Heretic
    "Knuckle Sandwitch" ,
    "Longhorn"          ,
    "Strucker"          ,
    "Pulverizer"        ,
    "Mourning Glory"    , "Matriarch" , "Dynamite",
    "Augur"             ,
    "Golden Emperor"    , "Old Dreadful"
  },

  { // Guncaster - Doom
    "Knuckle Sandwitch" ,
    "Longhorn"          ,
    "Ironblast"         , "Strucker",
    "Pulverizer"        ,
    "Mourning Glory"    , "Matriarch" , "Dynamite",
    "Augur"             ,
    "Golden Emperor"    , "Old Dreadful"
  },

  { // Guncaster - Hexen
    "Knuckle Sandwitch" ,
    "Longhorn"          ,
    "Ironblast"         , "Strucker",
    "Pulverizer"        ,
    "Mourning Glory"    , "Matriarch" , "Dynamite",
    "Augur"             ,
    "Golden Emperor"    , "Old Dreadful"
  },

  { // Guncaster - Strife
    "Knuckle Sandwitch" ,
    "Longhorn"          ,
    "Ironblast"         , "Strucker",
    "Pulverizer"        ,
    "Mourning Glory"    , "Matriarch" , "Dynamite",
    "Augur"             ,
    "Golden Emperor"    , "Old Dreadful"
  },

}; // end of printable names

// used in fallback mode
int priority[MAX_WEAPONS_NUMBER];
