// Game Detection Section //////////////////////////////////////////////////////

function bool WM_IsRekkr(void)
{
  return ScriptCall("wm_Game", "isRekkr");
}

function bool WM_IsAbortM(void)
{
  bool isAbortM = CheckClass("AbortButton");
  return isAbortM;
}

function bool WM_IsCyanDoom(void)
{
  bool isCyanDoom = CheckClass("STMinigun")
    && CheckClass("Daedabus")
    && CheckClass("VitalitySerum");
  return isCyanDoom;
}
